// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.MobileUsersAuth;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MobileUsersAuth_Roo_Configurable {
    
    declare @type: MobileUsersAuth: @Configurable;
    
}
