// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

import com.huazhuo.shop.bill.ShopBill;
import com.huazhuo.shop.bill.ShopBillDetail;
import com.huazhuo.shop.city.Areas;
import com.huazhuo.shop.city.Cities;
import com.huazhuo.shop.city.Locality;
import com.huazhuo.shop.city.Provinces;
import com.huazhuo.shop.domain.Company;
import com.huazhuo.shop.domain.MobileUsers;
import com.huazhuo.shop.domain.ProductBrand;
import com.huazhuo.shop.domain.ShopAddress;
import com.huazhuo.shop.domain.ShopFastMail;
import com.huazhuo.shop.domain.ShopFreightTemplate;
import com.huazhuo.shop.domain.ShopFreightTemplateDetail;
import com.huazhuo.shop.domain.ShopFreightTemplateDetailCity;
import com.huazhuo.shop.domain.ShopOrderEvaluate;
import com.huazhuo.shop.domain.ShopOrderEvaluateImg;
import com.huazhuo.shop.domain.ShopOrderEvaluateReply;
import com.huazhuo.shop.domain.ShopOrderList;
import com.huazhuo.shop.domain.ShopOrderRetrun;
import com.huazhuo.shop.domain.ShopOrderReturnConsult;
import com.huazhuo.shop.domain.ShopOrderReturnImg;
import com.huazhuo.shop.domain.ShopOrders;
import com.huazhuo.shop.domain.ShoppingCategories;
import com.huazhuo.shop.domain.ShoppingCategorySpecialMarks;
import com.huazhuo.shop.domain.ShoppingProductMark;
import com.huazhuo.shop.domain.ShoppingProductPictures;
import com.huazhuo.shop.domain.ShoppingProductType;
import com.huazhuo.shop.domain.ShoppingProducts;
import com.huazhuo.shop.domain.ShoppingProductsParameter;
import com.huazhuo.shop.domain.ShoppingProductsSpec;
import com.huazhuo.shop.domain.Shops;
import com.huazhuo.shop.domain.SpecialMarks;
import com.huazhuo.shop.enumtype.LogisticsCompany;
import com.huazhuo.shop.enumtype.ShopFreightTemplateType;
import com.huazhuo.shop.enumtype.ShopOrderRetrunType;
import com.huazhuo.shop.enumtype.ShopOrderType;
import com.huazhuo.shop.enumtype.SysLogType;
import com.huazhuo.shop.log.SysLog;
import com.huazhuo.shop.quartz.ScheduleJob;
import com.huazhuo.shop.security.BackAuthority;
import com.huazhuo.shop.security.BackGroupAuthority;
import com.huazhuo.shop.security.BackGroupMembers;
import com.huazhuo.shop.security.BackGroups;
import com.huazhuo.shop.security.BackUser;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<ShopBill, String> ApplicationConversionServiceFactoryBean.getShopBillToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.bill.ShopBill, java.lang.String>() {
            public String convert(ShopBill shopBill) {
                return new StringBuilder().append(shopBill.getBillNumber()).append(" ").append(shopBill.getBillStart()).append(" ").append(shopBill.getBillEnd()).append(" ").append(shopBill.getCreateDate()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopBill> ApplicationConversionServiceFactoryBean.getIdToShopBillConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.bill.ShopBill>() {
            public com.huazhuo.shop.bill.ShopBill convert(java.lang.Integer id) {
                return ShopBill.findShopBill(id);
            }
        };
    }
    
    public Converter<String, ShopBill> ApplicationConversionServiceFactoryBean.getStringToShopBillConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.bill.ShopBill>() {
            public com.huazhuo.shop.bill.ShopBill convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopBill.class);
            }
        };
    }
    
    public Converter<ShopBillDetail, String> ApplicationConversionServiceFactoryBean.getShopBillDetailToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.bill.ShopBillDetail, java.lang.String>() {
            public String convert(ShopBillDetail shopBillDetail) {
                return new StringBuilder().append(shopBillDetail.getOrderCost()).append(" ").append(shopBillDetail.getOrderSettleCost()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopBillDetail> ApplicationConversionServiceFactoryBean.getIdToShopBillDetailConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.bill.ShopBillDetail>() {
            public com.huazhuo.shop.bill.ShopBillDetail convert(java.lang.Integer id) {
                return ShopBillDetail.findShopBillDetail(id);
            }
        };
    }
    
    public Converter<String, ShopBillDetail> ApplicationConversionServiceFactoryBean.getStringToShopBillDetailConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.bill.ShopBillDetail>() {
            public com.huazhuo.shop.bill.ShopBillDetail convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopBillDetail.class);
            }
        };
    }
    
    public Converter<Areas, String> ApplicationConversionServiceFactoryBean.getAreasToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.city.Areas, java.lang.String>() {
            public String convert(Areas areas) {
                return new StringBuilder().append(areas.getCityId()).append(" ").append(areas.getCityName()).append(" ").append(areas.getAreaName()).append(" ").append(areas.getProvinceId()).toString();
            }
        };
    }
    
    public Converter<Integer, Areas> ApplicationConversionServiceFactoryBean.getIdToAreasConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.city.Areas>() {
            public com.huazhuo.shop.city.Areas convert(java.lang.Integer id) {
                return Areas.findAreas(id);
            }
        };
    }
    
    public Converter<String, Areas> ApplicationConversionServiceFactoryBean.getStringToAreasConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.city.Areas>() {
            public com.huazhuo.shop.city.Areas convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Areas.class);
            }
        };
    }
    
    public Converter<Cities, String> ApplicationConversionServiceFactoryBean.getCitiesToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.city.Cities, java.lang.String>() {
            public String convert(Cities cities) {
                return new StringBuilder().append(cities.getName()).append(" ").append(cities.getPinyin()).append(" ").append(cities.getPinyinAbridge()).append(" ").append(cities.getInitial()).toString();
            }
        };
    }
    
    public Converter<Integer, Cities> ApplicationConversionServiceFactoryBean.getIdToCitiesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.city.Cities>() {
            public com.huazhuo.shop.city.Cities convert(java.lang.Integer id) {
                return Cities.findCities(id);
            }
        };
    }
    
    public Converter<String, Cities> ApplicationConversionServiceFactoryBean.getStringToCitiesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.city.Cities>() {
            public com.huazhuo.shop.city.Cities convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Cities.class);
            }
        };
    }
    
    public Converter<Locality, String> ApplicationConversionServiceFactoryBean.getLocalityToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.city.Locality, java.lang.String>() {
            public String convert(Locality locality) {
                return new StringBuilder().append(locality.getName()).toString();
            }
        };
    }
    
    public Converter<Integer, Locality> ApplicationConversionServiceFactoryBean.getIdToLocalityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.city.Locality>() {
            public com.huazhuo.shop.city.Locality convert(java.lang.Integer id) {
                return Locality.findLocality(id);
            }
        };
    }
    
    public Converter<String, Locality> ApplicationConversionServiceFactoryBean.getStringToLocalityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.city.Locality>() {
            public com.huazhuo.shop.city.Locality convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Locality.class);
            }
        };
    }
    
    public Converter<Provinces, String> ApplicationConversionServiceFactoryBean.getProvincesToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.city.Provinces, java.lang.String>() {
            public String convert(Provinces provinces) {
                return new StringBuilder().append(provinces.getProvinceName()).append(" ").append(provinces.getIndexId()).append(" ").append(provinces.getSpell()).toString();
            }
        };
    }
    
    public Converter<Integer, Provinces> ApplicationConversionServiceFactoryBean.getIdToProvincesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.city.Provinces>() {
            public com.huazhuo.shop.city.Provinces convert(java.lang.Integer id) {
                return Provinces.findProvinces(id);
            }
        };
    }
    
    public Converter<String, Provinces> ApplicationConversionServiceFactoryBean.getStringToProvincesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.city.Provinces>() {
            public com.huazhuo.shop.city.Provinces convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Provinces.class);
            }
        };
    }
    
    public Converter<Company, String> ApplicationConversionServiceFactoryBean.getCompanyToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.Company, java.lang.String>() {
            public String convert(Company company) {
                return new StringBuilder().append(company.getName()).append(" ").append(company.getImgUrl()).append(" ").append(company.getAddress()).append(" ").append(company.getLegalPersion()).toString();
            }
        };
    }
    
    public Converter<Integer, Company> ApplicationConversionServiceFactoryBean.getIdToCompanyConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.Company>() {
            public com.huazhuo.shop.domain.Company convert(java.lang.Integer id) {
                return Company.findCompany(id);
            }
        };
    }
    
    public Converter<String, Company> ApplicationConversionServiceFactoryBean.getStringToCompanyConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.Company>() {
            public com.huazhuo.shop.domain.Company convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Company.class);
            }
        };
    }
    
    public Converter<MobileUsers, String> ApplicationConversionServiceFactoryBean.getMobileUsersToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.MobileUsers, java.lang.String>() {
            public String convert(MobileUsers mobileUsers) {
                return new StringBuilder().append(mobileUsers.getUserName()).toString();
            }
        };
    }
    
    public Converter<Integer, MobileUsers> ApplicationConversionServiceFactoryBean.getIdToMobileUsersConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.MobileUsers>() {
            public com.huazhuo.shop.domain.MobileUsers convert(java.lang.Integer id) {
                return MobileUsers.findMobileUsers(id);
            }
        };
    }
    
    public Converter<String, MobileUsers> ApplicationConversionServiceFactoryBean.getStringToMobileUsersConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.MobileUsers>() {
            public com.huazhuo.shop.domain.MobileUsers convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), MobileUsers.class);
            }
        };
    }
    
    public Converter<ProductBrand, String> ApplicationConversionServiceFactoryBean.getProductBrandToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ProductBrand, java.lang.String>() {
            public String convert(ProductBrand productBrand) {
                return new StringBuilder().append(productBrand.getBrandName()).append(" ").append(productBrand.getBrandStory()).append(" ").append(productBrand.getCreatedBy()).append(" ").append(productBrand.getCreatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, ProductBrand> ApplicationConversionServiceFactoryBean.getIdToProductBrandConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ProductBrand>() {
            public com.huazhuo.shop.domain.ProductBrand convert(java.lang.Integer id) {
                return ProductBrand.findProductBrand(id);
            }
        };
    }
    
    public Converter<String, ProductBrand> ApplicationConversionServiceFactoryBean.getStringToProductBrandConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ProductBrand>() {
            public com.huazhuo.shop.domain.ProductBrand convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ProductBrand.class);
            }
        };
    }
    
    public Converter<ShopAddress, String> ApplicationConversionServiceFactoryBean.getShopAddressToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopAddress, java.lang.String>() {
            public String convert(ShopAddress shopAddress) {
                return new StringBuilder().append(shopAddress.getContact()).append(" ").append(shopAddress.getAddress()).append(" ").append(shopAddress.getZipcood()).append(" ").append(shopAddress.getPhoneNumber()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopAddress> ApplicationConversionServiceFactoryBean.getIdToShopAddressConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopAddress>() {
            public com.huazhuo.shop.domain.ShopAddress convert(java.lang.Integer id) {
                return ShopAddress.findShopAddress(id);
            }
        };
    }
    
    public Converter<String, ShopAddress> ApplicationConversionServiceFactoryBean.getStringToShopAddressConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopAddress>() {
            public com.huazhuo.shop.domain.ShopAddress convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopAddress.class);
            }
        };
    }
    
    public Converter<ShopFastMail, String> ApplicationConversionServiceFactoryBean.getShopFastMailToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopFastMail, java.lang.String>() {
            public String convert(ShopFastMail shopFastMail) {
                return new StringBuilder().append(shopFastMail.getShopId()).append(" ").append(shopFastMail.getMailName()).append(" ").append(shopFastMail.getCost()).append(" ").append(shopFastMail.getDefCheck()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopFastMail> ApplicationConversionServiceFactoryBean.getIdToShopFastMailConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopFastMail>() {
            public com.huazhuo.shop.domain.ShopFastMail convert(java.lang.Integer id) {
                return ShopFastMail.findShopFastMail(id);
            }
        };
    }
    
    public Converter<String, ShopFastMail> ApplicationConversionServiceFactoryBean.getStringToShopFastMailConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopFastMail>() {
            public com.huazhuo.shop.domain.ShopFastMail convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopFastMail.class);
            }
        };
    }
    
    public Converter<ShopFreightTemplate, String> ApplicationConversionServiceFactoryBean.getShopFreightTemplateToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopFreightTemplate, java.lang.String>() {
            public String convert(ShopFreightTemplate shopFreightTemplate) {
                return new StringBuilder().append(shopFreightTemplate.getName()).append(" ").append(shopFreightTemplate.getSetType()).append(" ").append(shopFreightTemplate.getBilling()).append(" ").append(shopFreightTemplate.getShipping()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopFreightTemplate> ApplicationConversionServiceFactoryBean.getIdToShopFreightTemplateConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopFreightTemplate>() {
            public com.huazhuo.shop.domain.ShopFreightTemplate convert(java.lang.Integer id) {
                return ShopFreightTemplate.findShopFreightTemplate(id);
            }
        };
    }
    
    public Converter<String, ShopFreightTemplate> ApplicationConversionServiceFactoryBean.getStringToShopFreightTemplateConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopFreightTemplate>() {
            public com.huazhuo.shop.domain.ShopFreightTemplate convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopFreightTemplate.class);
            }
        };
    }
    
    public Converter<ShopFreightTemplateDetail, String> ApplicationConversionServiceFactoryBean.getShopFreightTemplateDetailToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopFreightTemplateDetail, java.lang.String>() {
            public String convert(ShopFreightTemplateDetail shopFreightTemplateDetail) {
                return new StringBuilder().append(shopFreightTemplateDetail.getCount()).append(" ").append(shopFreightTemplateDetail.getFreight()).append(" ").append(shopFreightTemplateDetail.getAddCount()).append(" ").append(shopFreightTemplateDetail.getAddFreight()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopFreightTemplateDetail> ApplicationConversionServiceFactoryBean.getIdToShopFreightTemplateDetailConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopFreightTemplateDetail>() {
            public com.huazhuo.shop.domain.ShopFreightTemplateDetail convert(java.lang.Integer id) {
                return ShopFreightTemplateDetail.findShopFreightTemplateDetail(id);
            }
        };
    }
    
    public Converter<String, ShopFreightTemplateDetail> ApplicationConversionServiceFactoryBean.getStringToShopFreightTemplateDetailConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopFreightTemplateDetail>() {
            public com.huazhuo.shop.domain.ShopFreightTemplateDetail convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopFreightTemplateDetail.class);
            }
        };
    }
    
    public Converter<ShopFreightTemplateDetailCity, String> ApplicationConversionServiceFactoryBean.getShopFreightTemplateDetailCityToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopFreightTemplateDetailCity, java.lang.String>() {
            public String convert(ShopFreightTemplateDetailCity shopFreightTemplateDetailCity) {
                return new StringBuilder().toString();
            }
        };
    }
    
    public Converter<Integer, ShopFreightTemplateDetailCity> ApplicationConversionServiceFactoryBean.getIdToShopFreightTemplateDetailCityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopFreightTemplateDetailCity>() {
            public com.huazhuo.shop.domain.ShopFreightTemplateDetailCity convert(java.lang.Integer id) {
                return ShopFreightTemplateDetailCity.findShopFreightTemplateDetailCity(id);
            }
        };
    }
    
    public Converter<String, ShopFreightTemplateDetailCity> ApplicationConversionServiceFactoryBean.getStringToShopFreightTemplateDetailCityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopFreightTemplateDetailCity>() {
            public com.huazhuo.shop.domain.ShopFreightTemplateDetailCity convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopFreightTemplateDetailCity.class);
            }
        };
    }
    
    public Converter<ShopOrderEvaluate, String> ApplicationConversionServiceFactoryBean.getShopOrderEvaluateToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopOrderEvaluate, java.lang.String>() {
            public String convert(ShopOrderEvaluate shopOrderEvaluate) {
                return new StringBuilder().append(shopOrderEvaluate.getContent()).append(" ").append(shopOrderEvaluate.getGrade()).append(" ").append(shopOrderEvaluate.getCreatedAt()).append(" ").append(shopOrderEvaluate.getUpdatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderEvaluate> ApplicationConversionServiceFactoryBean.getIdToShopOrderEvaluateConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopOrderEvaluate>() {
            public com.huazhuo.shop.domain.ShopOrderEvaluate convert(java.lang.Integer id) {
                return ShopOrderEvaluate.findShopOrderEvaluate(id);
            }
        };
    }
    
    public Converter<String, ShopOrderEvaluate> ApplicationConversionServiceFactoryBean.getStringToShopOrderEvaluateConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopOrderEvaluate>() {
            public com.huazhuo.shop.domain.ShopOrderEvaluate convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderEvaluate.class);
            }
        };
    }
    
    public Converter<ShopOrderEvaluateImg, String> ApplicationConversionServiceFactoryBean.getShopOrderEvaluateImgToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopOrderEvaluateImg, java.lang.String>() {
            public String convert(ShopOrderEvaluateImg shopOrderEvaluateImg) {
                return new StringBuilder().append(shopOrderEvaluateImg.getImgUrl()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderEvaluateImg> ApplicationConversionServiceFactoryBean.getIdToShopOrderEvaluateImgConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopOrderEvaluateImg>() {
            public com.huazhuo.shop.domain.ShopOrderEvaluateImg convert(java.lang.Integer id) {
                return ShopOrderEvaluateImg.findShopOrderEvaluateImg(id);
            }
        };
    }
    
    public Converter<String, ShopOrderEvaluateImg> ApplicationConversionServiceFactoryBean.getStringToShopOrderEvaluateImgConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopOrderEvaluateImg>() {
            public com.huazhuo.shop.domain.ShopOrderEvaluateImg convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderEvaluateImg.class);
            }
        };
    }
    
    public Converter<ShopOrderEvaluateReply, String> ApplicationConversionServiceFactoryBean.getShopOrderEvaluateReplyToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopOrderEvaluateReply, java.lang.String>() {
            public String convert(ShopOrderEvaluateReply shopOrderEvaluateReply) {
                return new StringBuilder().append(shopOrderEvaluateReply.getContent()).append(" ").append(shopOrderEvaluateReply.getCreatedAt()).append(" ").append(shopOrderEvaluateReply.getUpdatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderEvaluateReply> ApplicationConversionServiceFactoryBean.getIdToShopOrderEvaluateReplyConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopOrderEvaluateReply>() {
            public com.huazhuo.shop.domain.ShopOrderEvaluateReply convert(java.lang.Integer id) {
                return ShopOrderEvaluateReply.findShopOrderEvaluateReply(id);
            }
        };
    }
    
    public Converter<String, ShopOrderEvaluateReply> ApplicationConversionServiceFactoryBean.getStringToShopOrderEvaluateReplyConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopOrderEvaluateReply>() {
            public com.huazhuo.shop.domain.ShopOrderEvaluateReply convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderEvaluateReply.class);
            }
        };
    }
    
    public Converter<ShopOrderList, String> ApplicationConversionServiceFactoryBean.getShopOrderListToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopOrderList, java.lang.String>() {
            public String convert(ShopOrderList shopOrderList) {
                return new StringBuilder().append(shopOrderList.getBuyCouts()).append(" ").append(shopOrderList.getProductName()).append(" ").append(shopOrderList.getProductProperty()).append(" ").append(shopOrderList.getPrice()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderList> ApplicationConversionServiceFactoryBean.getIdToShopOrderListConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopOrderList>() {
            public com.huazhuo.shop.domain.ShopOrderList convert(java.lang.Integer id) {
                return ShopOrderList.findShopOrderList(id);
            }
        };
    }
    
    public Converter<String, ShopOrderList> ApplicationConversionServiceFactoryBean.getStringToShopOrderListConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopOrderList>() {
            public com.huazhuo.shop.domain.ShopOrderList convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderList.class);
            }
        };
    }
    
    public Converter<ShopOrderRetrun, String> ApplicationConversionServiceFactoryBean.getShopOrderRetrunToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopOrderRetrun, java.lang.String>() {
            public String convert(ShopOrderRetrun shopOrderRetrun) {
                return new StringBuilder().append(shopOrderRetrun.getReturnNumber()).append(" ").append(shopOrderRetrun.getReturnTime()).append(" ").append(shopOrderRetrun.getReturnCost()).append(" ").append(shopOrderRetrun.getCreatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderRetrun> ApplicationConversionServiceFactoryBean.getIdToShopOrderRetrunConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopOrderRetrun>() {
            public com.huazhuo.shop.domain.ShopOrderRetrun convert(java.lang.Integer id) {
                return ShopOrderRetrun.findShopOrderRetrun(id);
            }
        };
    }
    
    public Converter<String, ShopOrderRetrun> ApplicationConversionServiceFactoryBean.getStringToShopOrderRetrunConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopOrderRetrun>() {
            public com.huazhuo.shop.domain.ShopOrderRetrun convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderRetrun.class);
            }
        };
    }
    
    public Converter<ShopOrderReturnConsult, String> ApplicationConversionServiceFactoryBean.getShopOrderReturnConsultToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopOrderReturnConsult, java.lang.String>() {
            public String convert(ShopOrderReturnConsult shopOrderReturnConsult) {
                return new StringBuilder().append(shopOrderReturnConsult.getContent()).append(" ").append(shopOrderReturnConsult.getCreatedAt()).append(" ").append(shopOrderReturnConsult.getUpdatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderReturnConsult> ApplicationConversionServiceFactoryBean.getIdToShopOrderReturnConsultConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopOrderReturnConsult>() {
            public com.huazhuo.shop.domain.ShopOrderReturnConsult convert(java.lang.Integer id) {
                return ShopOrderReturnConsult.findShopOrderReturnConsult(id);
            }
        };
    }
    
    public Converter<String, ShopOrderReturnConsult> ApplicationConversionServiceFactoryBean.getStringToShopOrderReturnConsultConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopOrderReturnConsult>() {
            public com.huazhuo.shop.domain.ShopOrderReturnConsult convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderReturnConsult.class);
            }
        };
    }
    
    public Converter<ShopOrderReturnImg, String> ApplicationConversionServiceFactoryBean.getShopOrderReturnImgToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopOrderReturnImg, java.lang.String>() {
            public String convert(ShopOrderReturnImg shopOrderReturnImg) {
                return new StringBuilder().append(shopOrderReturnImg.getImgUrl()).append(" ").append(shopOrderReturnImg.getCreatedAt()).append(" ").append(shopOrderReturnImg.getUpdatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderReturnImg> ApplicationConversionServiceFactoryBean.getIdToShopOrderReturnImgConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopOrderReturnImg>() {
            public com.huazhuo.shop.domain.ShopOrderReturnImg convert(java.lang.Integer id) {
                return ShopOrderReturnImg.findShopOrderReturnImg(id);
            }
        };
    }
    
    public Converter<String, ShopOrderReturnImg> ApplicationConversionServiceFactoryBean.getStringToShopOrderReturnImgConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopOrderReturnImg>() {
            public com.huazhuo.shop.domain.ShopOrderReturnImg convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderReturnImg.class);
            }
        };
    }
    
    public Converter<ShopOrders, String> ApplicationConversionServiceFactoryBean.getShopOrdersToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShopOrders, java.lang.String>() {
            public String convert(ShopOrders shopOrders) {
                return new StringBuilder().append(shopOrders.getOrderNumber()).append(" ").append(shopOrders.getRemarks()).append(" ").append(shopOrders.getShopId()).append(" ").append(shopOrders.getOrderTime()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrders> ApplicationConversionServiceFactoryBean.getIdToShopOrdersConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShopOrders>() {
            public com.huazhuo.shop.domain.ShopOrders convert(java.lang.Integer id) {
                return ShopOrders.findShopOrders(id);
            }
        };
    }
    
    public Converter<String, ShopOrders> ApplicationConversionServiceFactoryBean.getStringToShopOrdersConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShopOrders>() {
            public com.huazhuo.shop.domain.ShopOrders convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrders.class);
            }
        };
    }
    
    public Converter<ShoppingCategories, String> ApplicationConversionServiceFactoryBean.getShoppingCategoriesToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShoppingCategories, java.lang.String>() {
            public String convert(ShoppingCategories shoppingCategories) {
                return new StringBuilder().append(shoppingCategories.getName()).append(" ").append(shoppingCategories.getDescription()).append(" ").append(shoppingCategories.getImage()).append(" ").append(shoppingCategories.getStatus()).toString();
            }
        };
    }
    
    public Converter<Integer, ShoppingCategories> ApplicationConversionServiceFactoryBean.getIdToShoppingCategoriesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShoppingCategories>() {
            public com.huazhuo.shop.domain.ShoppingCategories convert(java.lang.Integer id) {
                return ShoppingCategories.findShoppingCategories(id);
            }
        };
    }
    
    public Converter<String, ShoppingCategories> ApplicationConversionServiceFactoryBean.getStringToShoppingCategoriesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShoppingCategories>() {
            public com.huazhuo.shop.domain.ShoppingCategories convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShoppingCategories.class);
            }
        };
    }
    
    public Converter<ShoppingCategorySpecialMarks, String> ApplicationConversionServiceFactoryBean.getShoppingCategorySpecialMarksToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShoppingCategorySpecialMarks, java.lang.String>() {
            public String convert(ShoppingCategorySpecialMarks shoppingCategorySpecialMarks) {
                return new StringBuilder().append(shoppingCategorySpecialMarks.getShoppingCategoryId()).append(" ").append(shoppingCategorySpecialMarks.getSpecialMarkId()).toString();
            }
        };
    }
    
    public Converter<Integer, ShoppingCategorySpecialMarks> ApplicationConversionServiceFactoryBean.getIdToShoppingCategorySpecialMarksConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShoppingCategorySpecialMarks>() {
            public com.huazhuo.shop.domain.ShoppingCategorySpecialMarks convert(java.lang.Integer id) {
                return ShoppingCategorySpecialMarks.findShoppingCategorySpecialMarks(id);
            }
        };
    }
    
    public Converter<String, ShoppingCategorySpecialMarks> ApplicationConversionServiceFactoryBean.getStringToShoppingCategorySpecialMarksConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShoppingCategorySpecialMarks>() {
            public com.huazhuo.shop.domain.ShoppingCategorySpecialMarks convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShoppingCategorySpecialMarks.class);
            }
        };
    }
    
    public Converter<ShoppingProductMark, String> ApplicationConversionServiceFactoryBean.getShoppingProductMarkToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShoppingProductMark, java.lang.String>() {
            public String convert(ShoppingProductMark shoppingProductMark) {
                return new StringBuilder().append(shoppingProductMark.getName()).append(" ").append(shoppingProductMark.getSpecialMarkCategoryId()).append(" ").append(shoppingProductMark.getCreatedAt()).append(" ").append(shoppingProductMark.getUpdatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, ShoppingProductMark> ApplicationConversionServiceFactoryBean.getIdToShoppingProductMarkConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShoppingProductMark>() {
            public com.huazhuo.shop.domain.ShoppingProductMark convert(java.lang.Integer id) {
                return ShoppingProductMark.findShoppingProductMark(id);
            }
        };
    }
    
    public Converter<String, ShoppingProductMark> ApplicationConversionServiceFactoryBean.getStringToShoppingProductMarkConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShoppingProductMark>() {
            public com.huazhuo.shop.domain.ShoppingProductMark convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShoppingProductMark.class);
            }
        };
    }
    
    public Converter<ShoppingProductPictures, String> ApplicationConversionServiceFactoryBean.getShoppingProductPicturesToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShoppingProductPictures, java.lang.String>() {
            public String convert(ShoppingProductPictures shoppingProductPictures) {
                return new StringBuilder().append(shoppingProductPictures.getImage()).append(" ").append(shoppingProductPictures.getName()).append(" ").append(shoppingProductPictures.getCreatedAt()).append(" ").append(shoppingProductPictures.getUpdatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, ShoppingProductPictures> ApplicationConversionServiceFactoryBean.getIdToShoppingProductPicturesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShoppingProductPictures>() {
            public com.huazhuo.shop.domain.ShoppingProductPictures convert(java.lang.Integer id) {
                return ShoppingProductPictures.findShoppingProductPictures(id);
            }
        };
    }
    
    public Converter<String, ShoppingProductPictures> ApplicationConversionServiceFactoryBean.getStringToShoppingProductPicturesConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShoppingProductPictures>() {
            public com.huazhuo.shop.domain.ShoppingProductPictures convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShoppingProductPictures.class);
            }
        };
    }
    
    public Converter<ShoppingProductType, String> ApplicationConversionServiceFactoryBean.getShoppingProductTypeToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShoppingProductType, java.lang.String>() {
            public String convert(ShoppingProductType shoppingProductType) {
                return new StringBuilder().append(shoppingProductType.getTypeName()).append(" ").append(shoppingProductType.getTypeValue()).toString();
            }
        };
    }
    
    public Converter<Integer, ShoppingProductType> ApplicationConversionServiceFactoryBean.getIdToShoppingProductTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShoppingProductType>() {
            public com.huazhuo.shop.domain.ShoppingProductType convert(java.lang.Integer id) {
                return ShoppingProductType.findShoppingProductType(id);
            }
        };
    }
    
    public Converter<String, ShoppingProductType> ApplicationConversionServiceFactoryBean.getStringToShoppingProductTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShoppingProductType>() {
            public com.huazhuo.shop.domain.ShoppingProductType convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShoppingProductType.class);
            }
        };
    }
    
    public Converter<ShoppingProducts, String> ApplicationConversionServiceFactoryBean.getShoppingProductsToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShoppingProducts, java.lang.String>() {
            public String convert(ShoppingProducts shoppingProducts) {
                return new StringBuilder().append(shoppingProducts.getName()).append(" ").append(shoppingProducts.getSysNumber()).append(" ").append(shoppingProducts.getProductNumber()).append(" ").append(shoppingProducts.getOrgPrice()).toString();
            }
        };
    }
    
    public Converter<Integer, ShoppingProducts> ApplicationConversionServiceFactoryBean.getIdToShoppingProductsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShoppingProducts>() {
            public com.huazhuo.shop.domain.ShoppingProducts convert(java.lang.Integer id) {
                return ShoppingProducts.findShoppingProducts(id);
            }
        };
    }
    
    public Converter<String, ShoppingProducts> ApplicationConversionServiceFactoryBean.getStringToShoppingProductsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShoppingProducts>() {
            public com.huazhuo.shop.domain.ShoppingProducts convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShoppingProducts.class);
            }
        };
    }
    
    public Converter<ShoppingProductsParameter, String> ApplicationConversionServiceFactoryBean.getShoppingProductsParameterToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShoppingProductsParameter, java.lang.String>() {
            public String convert(ShoppingProductsParameter shoppingProductsParameter) {
                return new StringBuilder().append(shoppingProductsParameter.getParameterType()).append(" ").append(shoppingProductsParameter.getParameterValue()).toString();
            }
        };
    }
    
    public Converter<Integer, ShoppingProductsParameter> ApplicationConversionServiceFactoryBean.getIdToShoppingProductsParameterConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShoppingProductsParameter>() {
            public com.huazhuo.shop.domain.ShoppingProductsParameter convert(java.lang.Integer id) {
                return ShoppingProductsParameter.findShoppingProductsParameter(id);
            }
        };
    }
    
    public Converter<String, ShoppingProductsParameter> ApplicationConversionServiceFactoryBean.getStringToShoppingProductsParameterConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShoppingProductsParameter>() {
            public com.huazhuo.shop.domain.ShoppingProductsParameter convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShoppingProductsParameter.class);
            }
        };
    }
    
    public Converter<ShoppingProductsSpec, String> ApplicationConversionServiceFactoryBean.getShoppingProductsSpecToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.ShoppingProductsSpec, java.lang.String>() {
            public String convert(ShoppingProductsSpec shoppingProductsSpec) {
                return new StringBuilder().append(shoppingProductsSpec.getSpecName()).append(" ").append(shoppingProductsSpec.getOrgPrice()).append(" ").append(shoppingProductsSpec.getPrice()).toString();
            }
        };
    }
    
    public Converter<Integer, ShoppingProductsSpec> ApplicationConversionServiceFactoryBean.getIdToShoppingProductsSpecConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.ShoppingProductsSpec>() {
            public com.huazhuo.shop.domain.ShoppingProductsSpec convert(java.lang.Integer id) {
                return ShoppingProductsSpec.findShoppingProductsSpec(id);
            }
        };
    }
    
    public Converter<String, ShoppingProductsSpec> ApplicationConversionServiceFactoryBean.getStringToShoppingProductsSpecConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.ShoppingProductsSpec>() {
            public com.huazhuo.shop.domain.ShoppingProductsSpec convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShoppingProductsSpec.class);
            }
        };
    }
    
    public Converter<Shops, String> ApplicationConversionServiceFactoryBean.getShopsToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.Shops, java.lang.String>() {
            public String convert(Shops shops) {
                return new StringBuilder().append(shops.getName()).append(" ").append(shops.getUrl()).append(" ").append(shops.getContent()).append(" ").append(shops.getCreatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, Shops> ApplicationConversionServiceFactoryBean.getIdToShopsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.Shops>() {
            public com.huazhuo.shop.domain.Shops convert(java.lang.Integer id) {
                return Shops.findShops(id);
            }
        };
    }
    
    public Converter<String, Shops> ApplicationConversionServiceFactoryBean.getStringToShopsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.Shops>() {
            public com.huazhuo.shop.domain.Shops convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Shops.class);
            }
        };
    }
    
    public Converter<SpecialMarks, String> ApplicationConversionServiceFactoryBean.getSpecialMarksToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.domain.SpecialMarks, java.lang.String>() {
            public String convert(SpecialMarks specialMarks) {
                return new StringBuilder().append(specialMarks.getName()).append(" ").append(specialMarks.getCreatedAt()).append(" ").append(specialMarks.getUpdatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, SpecialMarks> ApplicationConversionServiceFactoryBean.getIdToSpecialMarksConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.domain.SpecialMarks>() {
            public com.huazhuo.shop.domain.SpecialMarks convert(java.lang.Integer id) {
                return SpecialMarks.findSpecialMarks(id);
            }
        };
    }
    
    public Converter<String, SpecialMarks> ApplicationConversionServiceFactoryBean.getStringToSpecialMarksConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.domain.SpecialMarks>() {
            public com.huazhuo.shop.domain.SpecialMarks convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), SpecialMarks.class);
            }
        };
    }
    
    public Converter<LogisticsCompany, String> ApplicationConversionServiceFactoryBean.getLogisticsCompanyToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.enumtype.LogisticsCompany, java.lang.String>() {
            public String convert(LogisticsCompany logisticsCompany) {
                return new StringBuilder().append(logisticsCompany.getLogisticsCode()).append(" ").append(logisticsCompany.getLogisticsName()).append(" ").append(logisticsCompany.getCompanyType()).append(" ").append(logisticsCompany.getCreatedAt()).toString();
            }
        };
    }
    
    public Converter<Integer, LogisticsCompany> ApplicationConversionServiceFactoryBean.getIdToLogisticsCompanyConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.enumtype.LogisticsCompany>() {
            public com.huazhuo.shop.enumtype.LogisticsCompany convert(java.lang.Integer id) {
                return LogisticsCompany.findLogisticsCompany(id);
            }
        };
    }
    
    public Converter<String, LogisticsCompany> ApplicationConversionServiceFactoryBean.getStringToLogisticsCompanyConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.enumtype.LogisticsCompany>() {
            public com.huazhuo.shop.enumtype.LogisticsCompany convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), LogisticsCompany.class);
            }
        };
    }
    
    public Converter<ShopFreightTemplateType, String> ApplicationConversionServiceFactoryBean.getShopFreightTemplateTypeToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.enumtype.ShopFreightTemplateType, java.lang.String>() {
            public String convert(ShopFreightTemplateType shopFreightTemplateType) {
                return new StringBuilder().append(shopFreightTemplateType.getName()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopFreightTemplateType> ApplicationConversionServiceFactoryBean.getIdToShopFreightTemplateTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.enumtype.ShopFreightTemplateType>() {
            public com.huazhuo.shop.enumtype.ShopFreightTemplateType convert(java.lang.Integer id) {
                return ShopFreightTemplateType.findShopFreightTemplateType(id);
            }
        };
    }
    
    public Converter<String, ShopFreightTemplateType> ApplicationConversionServiceFactoryBean.getStringToShopFreightTemplateTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.enumtype.ShopFreightTemplateType>() {
            public com.huazhuo.shop.enumtype.ShopFreightTemplateType convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopFreightTemplateType.class);
            }
        };
    }
    
    public Converter<ShopOrderRetrunType, String> ApplicationConversionServiceFactoryBean.getShopOrderRetrunTypeToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.enumtype.ShopOrderRetrunType, java.lang.String>() {
            public String convert(ShopOrderRetrunType shopOrderRetrunType) {
                return new StringBuilder().append(shopOrderRetrunType.getName()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderRetrunType> ApplicationConversionServiceFactoryBean.getIdToShopOrderRetrunTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.enumtype.ShopOrderRetrunType>() {
            public com.huazhuo.shop.enumtype.ShopOrderRetrunType convert(java.lang.Integer id) {
                return ShopOrderRetrunType.findShopOrderRetrunType(id);
            }
        };
    }
    
    public Converter<String, ShopOrderRetrunType> ApplicationConversionServiceFactoryBean.getStringToShopOrderRetrunTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.enumtype.ShopOrderRetrunType>() {
            public com.huazhuo.shop.enumtype.ShopOrderRetrunType convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderRetrunType.class);
            }
        };
    }
    
    public Converter<ShopOrderType, String> ApplicationConversionServiceFactoryBean.getShopOrderTypeToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.enumtype.ShopOrderType, java.lang.String>() {
            public String convert(ShopOrderType shopOrderType) {
                return new StringBuilder().append(shopOrderType.getName()).append(" ").append(shopOrderType.getState()).toString();
            }
        };
    }
    
    public Converter<Integer, ShopOrderType> ApplicationConversionServiceFactoryBean.getIdToShopOrderTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.enumtype.ShopOrderType>() {
            public com.huazhuo.shop.enumtype.ShopOrderType convert(java.lang.Integer id) {
                return ShopOrderType.findShopOrderType(id);
            }
        };
    }
    
    public Converter<String, ShopOrderType> ApplicationConversionServiceFactoryBean.getStringToShopOrderTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.enumtype.ShopOrderType>() {
            public com.huazhuo.shop.enumtype.ShopOrderType convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ShopOrderType.class);
            }
        };
    }
    
    public Converter<SysLogType, String> ApplicationConversionServiceFactoryBean.getSysLogTypeToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.enumtype.SysLogType, java.lang.String>() {
            public String convert(SysLogType sysLogType) {
                return new StringBuilder().append(sysLogType.getName()).append(" ").append(sysLogType.getState()).toString();
            }
        };
    }
    
    public Converter<Integer, SysLogType> ApplicationConversionServiceFactoryBean.getIdToSysLogTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.enumtype.SysLogType>() {
            public com.huazhuo.shop.enumtype.SysLogType convert(java.lang.Integer id) {
                return SysLogType.findSysLogType(id);
            }
        };
    }
    
    public Converter<String, SysLogType> ApplicationConversionServiceFactoryBean.getStringToSysLogTypeConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.enumtype.SysLogType>() {
            public com.huazhuo.shop.enumtype.SysLogType convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), SysLogType.class);
            }
        };
    }
    
    public Converter<SysLog, String> ApplicationConversionServiceFactoryBean.getSysLogToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.log.SysLog, java.lang.String>() {
            public String convert(SysLog sysLog) {
                return new StringBuilder().append(sysLog.getContent()).append(" ").append(sysLog.getOperator()).append(" ").append(sysLog.getProcessId()).append(" ").append(sysLog.getIp()).toString();
            }
        };
    }
    
    public Converter<Integer, SysLog> ApplicationConversionServiceFactoryBean.getIdToSysLogConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.log.SysLog>() {
            public com.huazhuo.shop.log.SysLog convert(java.lang.Integer id) {
                return SysLog.findSysLog(id);
            }
        };
    }
    
    public Converter<String, SysLog> ApplicationConversionServiceFactoryBean.getStringToSysLogConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.log.SysLog>() {
            public com.huazhuo.shop.log.SysLog convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), SysLog.class);
            }
        };
    }
    
    public Converter<ScheduleJob, String> ApplicationConversionServiceFactoryBean.getScheduleJobToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.quartz.ScheduleJob, java.lang.String>() {
            public String convert(ScheduleJob scheduleJob) {
                return new StringBuilder().append(scheduleJob.getJobName()).append(" ").append(scheduleJob.getJobGroup()).append(" ").append(scheduleJob.getJobStatus()).append(" ").append(scheduleJob.getCronExpression()).toString();
            }
        };
    }
    
    public Converter<Integer, ScheduleJob> ApplicationConversionServiceFactoryBean.getIdToScheduleJobConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.quartz.ScheduleJob>() {
            public com.huazhuo.shop.quartz.ScheduleJob convert(java.lang.Integer id) {
                return ScheduleJob.findScheduleJob(id);
            }
        };
    }
    
    public Converter<String, ScheduleJob> ApplicationConversionServiceFactoryBean.getStringToScheduleJobConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.quartz.ScheduleJob>() {
            public com.huazhuo.shop.quartz.ScheduleJob convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), ScheduleJob.class);
            }
        };
    }
    
    public Converter<BackAuthority, String> ApplicationConversionServiceFactoryBean.getBackAuthorityToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.security.BackAuthority, java.lang.String>() {
            public String convert(BackAuthority backAuthority) {
                return new StringBuilder().append(backAuthority.getAuthorityName()).append(" ").append(backAuthority.getName()).toString();
            }
        };
    }
    
    public Converter<Integer, BackAuthority> ApplicationConversionServiceFactoryBean.getIdToBackAuthorityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.security.BackAuthority>() {
            public com.huazhuo.shop.security.BackAuthority convert(java.lang.Integer id) {
                return BackAuthority.findBackAuthority(id);
            }
        };
    }
    
    public Converter<String, BackAuthority> ApplicationConversionServiceFactoryBean.getStringToBackAuthorityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.security.BackAuthority>() {
            public com.huazhuo.shop.security.BackAuthority convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), BackAuthority.class);
            }
        };
    }
    
    public Converter<BackGroupAuthority, String> ApplicationConversionServiceFactoryBean.getBackGroupAuthorityToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.security.BackGroupAuthority, java.lang.String>() {
            public String convert(BackGroupAuthority backGroupAuthority) {
                return new StringBuilder().toString();
            }
        };
    }
    
    public Converter<Integer, BackGroupAuthority> ApplicationConversionServiceFactoryBean.getIdToBackGroupAuthorityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.security.BackGroupAuthority>() {
            public com.huazhuo.shop.security.BackGroupAuthority convert(java.lang.Integer id) {
                return BackGroupAuthority.findBackGroupAuthority(id);
            }
        };
    }
    
    public Converter<String, BackGroupAuthority> ApplicationConversionServiceFactoryBean.getStringToBackGroupAuthorityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.security.BackGroupAuthority>() {
            public com.huazhuo.shop.security.BackGroupAuthority convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), BackGroupAuthority.class);
            }
        };
    }
    
    public Converter<BackGroupMembers, String> ApplicationConversionServiceFactoryBean.getBackGroupMembersToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.security.BackGroupMembers, java.lang.String>() {
            public String convert(BackGroupMembers backGroupMembers) {
                return new StringBuilder().toString();
            }
        };
    }
    
    public Converter<Integer, BackGroupMembers> ApplicationConversionServiceFactoryBean.getIdToBackGroupMembersConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.security.BackGroupMembers>() {
            public com.huazhuo.shop.security.BackGroupMembers convert(java.lang.Integer id) {
                return BackGroupMembers.findBackGroupMembers(id);
            }
        };
    }
    
    public Converter<String, BackGroupMembers> ApplicationConversionServiceFactoryBean.getStringToBackGroupMembersConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.security.BackGroupMembers>() {
            public com.huazhuo.shop.security.BackGroupMembers convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), BackGroupMembers.class);
            }
        };
    }
    
    public Converter<BackGroups, String> ApplicationConversionServiceFactoryBean.getBackGroupsToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.security.BackGroups, java.lang.String>() {
            public String convert(BackGroups backGroups) {
                return new StringBuilder().append(backGroups.getGroupName()).toString();
            }
        };
    }
    
    public Converter<Integer, BackGroups> ApplicationConversionServiceFactoryBean.getIdToBackGroupsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.security.BackGroups>() {
            public com.huazhuo.shop.security.BackGroups convert(java.lang.Integer id) {
                return BackGroups.findBackGroups(id);
            }
        };
    }
    
    public Converter<String, BackGroups> ApplicationConversionServiceFactoryBean.getStringToBackGroupsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.security.BackGroups>() {
            public com.huazhuo.shop.security.BackGroups convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), BackGroups.class);
            }
        };
    }
    
    public Converter<BackUser, String> ApplicationConversionServiceFactoryBean.getBackUserToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.huazhuo.shop.security.BackUser, java.lang.String>() {
            public String convert(BackUser backUser) {
                return new StringBuilder().append(backUser.getUserName()).append(" ").append(backUser.getFullName()).append(" ").append(backUser.getPassword()).append(" ").append(backUser.getCompanyName()).toString();
            }
        };
    }
    
    public Converter<Integer, BackUser> ApplicationConversionServiceFactoryBean.getIdToBackUserConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, com.huazhuo.shop.security.BackUser>() {
            public com.huazhuo.shop.security.BackUser convert(java.lang.Integer id) {
                return BackUser.findBackUser(id);
            }
        };
    }
    
    public Converter<String, BackUser> ApplicationConversionServiceFactoryBean.getStringToBackUserConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.huazhuo.shop.security.BackUser>() {
            public com.huazhuo.shop.security.BackUser convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), BackUser.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getShopBillToStringConverter());
        registry.addConverter(getIdToShopBillConverter());
        registry.addConverter(getStringToShopBillConverter());
        registry.addConverter(getShopBillDetailToStringConverter());
        registry.addConverter(getIdToShopBillDetailConverter());
        registry.addConverter(getStringToShopBillDetailConverter());
        registry.addConverter(getAreasToStringConverter());
        registry.addConverter(getIdToAreasConverter());
        registry.addConverter(getStringToAreasConverter());
        registry.addConverter(getCitiesToStringConverter());
        registry.addConverter(getIdToCitiesConverter());
        registry.addConverter(getStringToCitiesConverter());
        registry.addConverter(getLocalityToStringConverter());
        registry.addConverter(getIdToLocalityConverter());
        registry.addConverter(getStringToLocalityConverter());
        registry.addConverter(getProvincesToStringConverter());
        registry.addConverter(getIdToProvincesConverter());
        registry.addConverter(getStringToProvincesConverter());
        registry.addConverter(getCompanyToStringConverter());
        registry.addConverter(getIdToCompanyConverter());
        registry.addConverter(getStringToCompanyConverter());
        registry.addConverter(getMobileUsersToStringConverter());
        registry.addConverter(getIdToMobileUsersConverter());
        registry.addConverter(getStringToMobileUsersConverter());
        registry.addConverter(getProductBrandToStringConverter());
        registry.addConverter(getIdToProductBrandConverter());
        registry.addConverter(getStringToProductBrandConverter());
        registry.addConverter(getShopAddressToStringConverter());
        registry.addConverter(getIdToShopAddressConverter());
        registry.addConverter(getStringToShopAddressConverter());
        registry.addConverter(getShopFastMailToStringConverter());
        registry.addConverter(getIdToShopFastMailConverter());
        registry.addConverter(getStringToShopFastMailConverter());
        registry.addConverter(getShopFreightTemplateToStringConverter());
        registry.addConverter(getIdToShopFreightTemplateConverter());
        registry.addConverter(getStringToShopFreightTemplateConverter());
        registry.addConverter(getShopFreightTemplateDetailToStringConverter());
        registry.addConverter(getIdToShopFreightTemplateDetailConverter());
        registry.addConverter(getStringToShopFreightTemplateDetailConverter());
        registry.addConverter(getShopFreightTemplateDetailCityToStringConverter());
        registry.addConverter(getIdToShopFreightTemplateDetailCityConverter());
        registry.addConverter(getStringToShopFreightTemplateDetailCityConverter());
        registry.addConverter(getShopOrderEvaluateToStringConverter());
        registry.addConverter(getIdToShopOrderEvaluateConverter());
        registry.addConverter(getStringToShopOrderEvaluateConverter());
        registry.addConverter(getShopOrderEvaluateImgToStringConverter());
        registry.addConverter(getIdToShopOrderEvaluateImgConverter());
        registry.addConverter(getStringToShopOrderEvaluateImgConverter());
        registry.addConverter(getShopOrderEvaluateReplyToStringConverter());
        registry.addConverter(getIdToShopOrderEvaluateReplyConverter());
        registry.addConverter(getStringToShopOrderEvaluateReplyConverter());
        registry.addConverter(getShopOrderListToStringConverter());
        registry.addConverter(getIdToShopOrderListConverter());
        registry.addConverter(getStringToShopOrderListConverter());
        registry.addConverter(getShopOrderRetrunToStringConverter());
        registry.addConverter(getIdToShopOrderRetrunConverter());
        registry.addConverter(getStringToShopOrderRetrunConverter());
        registry.addConverter(getShopOrderReturnConsultToStringConverter());
        registry.addConverter(getIdToShopOrderReturnConsultConverter());
        registry.addConverter(getStringToShopOrderReturnConsultConverter());
        registry.addConverter(getShopOrderReturnImgToStringConverter());
        registry.addConverter(getIdToShopOrderReturnImgConverter());
        registry.addConverter(getStringToShopOrderReturnImgConverter());
        registry.addConverter(getShopOrdersToStringConverter());
        registry.addConverter(getIdToShopOrdersConverter());
        registry.addConverter(getStringToShopOrdersConverter());
        registry.addConverter(getShoppingCategoriesToStringConverter());
        registry.addConverter(getIdToShoppingCategoriesConverter());
        registry.addConverter(getStringToShoppingCategoriesConverter());
        registry.addConverter(getShoppingCategorySpecialMarksToStringConverter());
        registry.addConverter(getIdToShoppingCategorySpecialMarksConverter());
        registry.addConverter(getStringToShoppingCategorySpecialMarksConverter());
        registry.addConverter(getShoppingProductMarkToStringConverter());
        registry.addConverter(getIdToShoppingProductMarkConverter());
        registry.addConverter(getStringToShoppingProductMarkConverter());
        registry.addConverter(getShoppingProductPicturesToStringConverter());
        registry.addConverter(getIdToShoppingProductPicturesConverter());
        registry.addConverter(getStringToShoppingProductPicturesConverter());
        registry.addConverter(getShoppingProductTypeToStringConverter());
        registry.addConverter(getIdToShoppingProductTypeConverter());
        registry.addConverter(getStringToShoppingProductTypeConverter());
        registry.addConverter(getShoppingProductsToStringConverter());
        registry.addConverter(getIdToShoppingProductsConverter());
        registry.addConverter(getStringToShoppingProductsConverter());
        registry.addConverter(getShoppingProductsParameterToStringConverter());
        registry.addConverter(getIdToShoppingProductsParameterConverter());
        registry.addConverter(getStringToShoppingProductsParameterConverter());
        registry.addConverter(getShoppingProductsSpecToStringConverter());
        registry.addConverter(getIdToShoppingProductsSpecConverter());
        registry.addConverter(getStringToShoppingProductsSpecConverter());
        registry.addConverter(getShopsToStringConverter());
        registry.addConverter(getIdToShopsConverter());
        registry.addConverter(getStringToShopsConverter());
        registry.addConverter(getSpecialMarksToStringConverter());
        registry.addConverter(getIdToSpecialMarksConverter());
        registry.addConverter(getStringToSpecialMarksConverter());
        registry.addConverter(getLogisticsCompanyToStringConverter());
        registry.addConverter(getIdToLogisticsCompanyConverter());
        registry.addConverter(getStringToLogisticsCompanyConverter());
        registry.addConverter(getShopFreightTemplateTypeToStringConverter());
        registry.addConverter(getIdToShopFreightTemplateTypeConverter());
        registry.addConverter(getStringToShopFreightTemplateTypeConverter());
        registry.addConverter(getShopOrderRetrunTypeToStringConverter());
        registry.addConverter(getIdToShopOrderRetrunTypeConverter());
        registry.addConverter(getStringToShopOrderRetrunTypeConverter());
        registry.addConverter(getShopOrderTypeToStringConverter());
        registry.addConverter(getIdToShopOrderTypeConverter());
        registry.addConverter(getStringToShopOrderTypeConverter());
        registry.addConverter(getSysLogTypeToStringConverter());
        registry.addConverter(getIdToSysLogTypeConverter());
        registry.addConverter(getStringToSysLogTypeConverter());
        registry.addConverter(getSysLogToStringConverter());
        registry.addConverter(getIdToSysLogConverter());
        registry.addConverter(getStringToSysLogConverter());
        registry.addConverter(getScheduleJobToStringConverter());
        registry.addConverter(getIdToScheduleJobConverter());
        registry.addConverter(getStringToScheduleJobConverter());
        registry.addConverter(getBackAuthorityToStringConverter());
        registry.addConverter(getIdToBackAuthorityConverter());
        registry.addConverter(getStringToBackAuthorityConverter());
        registry.addConverter(getBackGroupAuthorityToStringConverter());
        registry.addConverter(getIdToBackGroupAuthorityConverter());
        registry.addConverter(getStringToBackGroupAuthorityConverter());
        registry.addConverter(getBackGroupMembersToStringConverter());
        registry.addConverter(getIdToBackGroupMembersConverter());
        registry.addConverter(getStringToBackGroupMembersConverter());
        registry.addConverter(getBackGroupsToStringConverter());
        registry.addConverter(getIdToBackGroupsConverter());
        registry.addConverter(getStringToBackGroupsConverter());
        registry.addConverter(getBackUserToStringConverter());
        registry.addConverter(getIdToBackUserConverter());
        registry.addConverter(getStringToBackUserConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
