// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.enumtype.ShopOrderRetrunType;

privileged aspect ShopOrderRetrunTypeController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ShopOrderRetrunTypeController.create(@Valid ShopOrderRetrunType shopOrderRetrunType, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderRetrunType);
            return "shoporderretruntypes/create";
        }
        uiModel.asMap().clear();
        shopOrderRetrunType.persist();
        return "redirect:/shoporderretruntypes/" + encodeUrlPathSegment(shopOrderRetrunType.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ShopOrderRetrunTypeController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ShopOrderRetrunType());
        return "shoporderretruntypes/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ShopOrderRetrunTypeController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("shoporderretruntype", ShopOrderRetrunType.findShopOrderRetrunType(id));
        uiModel.addAttribute("itemId", id);
        return "shoporderretruntypes/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ShopOrderRetrunTypeController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("shoporderretruntypes", ShopOrderRetrunType.findShopOrderRetrunTypeEntries(firstResult, sizeNo));
            float nrOfPages = (float) ShopOrderRetrunType.countShopOrderRetrunTypes() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("shoporderretruntypes", ShopOrderRetrunType.findAllShopOrderRetrunTypes());
        }
        return "shoporderretruntypes/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShopOrderRetrunTypeController.update(@Valid ShopOrderRetrunType shopOrderRetrunType, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderRetrunType);
            return "shoporderretruntypes/update";
        }
        uiModel.asMap().clear();
        shopOrderRetrunType.merge();
        return "redirect:/shoporderretruntypes/" + encodeUrlPathSegment(shopOrderRetrunType.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShopOrderRetrunTypeController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShopOrderRetrunType.findShopOrderRetrunType(id));
        return "shoporderretruntypes/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShopOrderRetrunTypeController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShopOrderRetrunType shopOrderRetrunType = ShopOrderRetrunType.findShopOrderRetrunType(id);
        shopOrderRetrunType.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shoporderretruntypes";
    }
    
    void ShopOrderRetrunTypeController.populateEditForm(Model uiModel, ShopOrderRetrunType shopOrderRetrunType) {
        uiModel.addAttribute("shopOrderRetrunType", shopOrderRetrunType);
    }
    
    String ShopOrderRetrunTypeController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
