// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;
import java.util.Arrays;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.bill.ShopBill;
import com.huazhuo.shop.bill.ShopBillDetail;
import com.huazhuo.shop.billenum.BillEnumDetail;
import com.huazhuo.shop.domain.ShopOrders;

privileged aspect ShopBillDetailController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ShopBillDetailController.create(@Valid ShopBillDetail shopBillDetail, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopBillDetail);
            return "shopbilldetails/create";
        }
        uiModel.asMap().clear();
        shopBillDetail.persist();
        return "redirect:/shopbilldetails/" + encodeUrlPathSegment(shopBillDetail.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ShopBillDetailController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ShopBillDetail());
        return "shopbilldetails/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ShopBillDetailController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("shopbilldetail", ShopBillDetail.findShopBillDetail(id));
        uiModel.addAttribute("itemId", id);
        return "shopbilldetails/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ShopBillDetailController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("shopbilldetails", ShopBillDetail.findShopBillDetailEntries(firstResult, sizeNo));
            float nrOfPages = (float) ShopBillDetail.countShopBillDetails() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("shopbilldetails", ShopBillDetail.findAllShopBillDetails());
        }
        return "shopbilldetails/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShopBillDetailController.update(@Valid ShopBillDetail shopBillDetail, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopBillDetail);
            return "shopbilldetails/update";
        }
        uiModel.asMap().clear();
        shopBillDetail.merge();
        return "redirect:/shopbilldetails/" + encodeUrlPathSegment(shopBillDetail.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShopBillDetailController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShopBillDetail.findShopBillDetail(id));
        return "shopbilldetails/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShopBillDetailController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShopBillDetail shopBillDetail = ShopBillDetail.findShopBillDetail(id);
        shopBillDetail.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shopbilldetails";
    }
    
    void ShopBillDetailController.populateEditForm(Model uiModel, ShopBillDetail shopBillDetail) {
        uiModel.addAttribute("shopBillDetail", shopBillDetail);
        uiModel.addAttribute("shopbills", ShopBill.findAllShopBills());
        uiModel.addAttribute("billenumdetails", Arrays.asList(BillEnumDetail.values()));
        uiModel.addAttribute("shoporderses", ShopOrders.findAllShopOrderses());
    }
    
    String ShopBillDetailController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
