// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.domain.ShopOrderList;
import com.huazhuo.shop.domain.ShopOrders;
import com.huazhuo.shop.domain.ShoppingProducts;

privileged aspect ShopOrderListController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ShopOrderListController.create(@Valid ShopOrderList shopOrderList, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderList);
            return "shoporderlists/create";
        }
        uiModel.asMap().clear();
        shopOrderList.persist();
        return "redirect:/shoporderlists/" + encodeUrlPathSegment(shopOrderList.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ShopOrderListController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ShopOrderList());
        return "shoporderlists/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ShopOrderListController.show(@PathVariable("id") Integer id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("shoporderlist", ShopOrderList.findShopOrderList(id));
        uiModel.addAttribute("itemId", id);
        return "shoporderlists/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ShopOrderListController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("shoporderlists", ShopOrderList.findShopOrderListEntries(firstResult, sizeNo));
            float nrOfPages = (float) ShopOrderList.countShopOrderLists() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("shoporderlists", ShopOrderList.findAllShopOrderLists());
        }
        addDateTimeFormatPatterns(uiModel);
        return "shoporderlists/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShopOrderListController.update(@Valid ShopOrderList shopOrderList, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderList);
            return "shoporderlists/update";
        }
        uiModel.asMap().clear();
        shopOrderList.merge();
        return "redirect:/shoporderlists/" + encodeUrlPathSegment(shopOrderList.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShopOrderListController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShopOrderList.findShopOrderList(id));
        return "shoporderlists/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShopOrderListController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShopOrderList shopOrderList = ShopOrderList.findShopOrderList(id);
        shopOrderList.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shoporderlists";
    }
    
    void ShopOrderListController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("shopOrderList_createdat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrderList_updatedat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
    }
    
    void ShopOrderListController.populateEditForm(Model uiModel, ShopOrderList shopOrderList) {
        uiModel.addAttribute("shopOrderList", shopOrderList);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("shoporderses", ShopOrders.findAllShopOrderses());
        uiModel.addAttribute("shoppingproductses", ShoppingProducts.findAllShoppingProductses());
    }
    
    String ShopOrderListController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
