// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.enumtype.ShopFreightTemplateType;

privileged aspect ShopFreightTemplateTypeController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ShopFreightTemplateTypeController.create(@Valid ShopFreightTemplateType shopFreightTemplateType, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopFreightTemplateType);
            return "shopfreighttemplatetypes/create";
        }
        uiModel.asMap().clear();
        shopFreightTemplateType.persist();
        return "redirect:/shopfreighttemplatetypes/" + encodeUrlPathSegment(shopFreightTemplateType.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ShopFreightTemplateTypeController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ShopFreightTemplateType());
        return "shopfreighttemplatetypes/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ShopFreightTemplateTypeController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("shopfreighttemplatetype", ShopFreightTemplateType.findShopFreightTemplateType(id));
        uiModel.addAttribute("itemId", id);
        return "shopfreighttemplatetypes/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ShopFreightTemplateTypeController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("shopfreighttemplatetypes", ShopFreightTemplateType.findShopFreightTemplateTypeEntries(firstResult, sizeNo));
            float nrOfPages = (float) ShopFreightTemplateType.countShopFreightTemplateTypes() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("shopfreighttemplatetypes", ShopFreightTemplateType.findAllShopFreightTemplateTypes());
        }
        return "shopfreighttemplatetypes/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShopFreightTemplateTypeController.update(@Valid ShopFreightTemplateType shopFreightTemplateType, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopFreightTemplateType);
            return "shopfreighttemplatetypes/update";
        }
        uiModel.asMap().clear();
        shopFreightTemplateType.merge();
        return "redirect:/shopfreighttemplatetypes/" + encodeUrlPathSegment(shopFreightTemplateType.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShopFreightTemplateTypeController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShopFreightTemplateType.findShopFreightTemplateType(id));
        return "shopfreighttemplatetypes/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShopFreightTemplateTypeController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShopFreightTemplateType shopFreightTemplateType = ShopFreightTemplateType.findShopFreightTemplateType(id);
        shopFreightTemplateType.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shopfreighttemplatetypes";
    }
    
    void ShopFreightTemplateTypeController.populateEditForm(Model uiModel, ShopFreightTemplateType shopFreightTemplateType) {
        uiModel.addAttribute("shopFreightTemplateType", shopFreightTemplateType);
    }
    
    String ShopFreightTemplateTypeController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
