// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.domain.ShoppingProductMark;
import com.huazhuo.shop.domain.ShoppingProducts;

privileged aspect ShoppingProductMarkController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ShoppingProductMarkController.create(@Valid ShoppingProductMark shoppingProductMark, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shoppingProductMark);
            return "shoppingproductmarks/create";
        }
        uiModel.asMap().clear();
        shoppingProductMark.persist();
        return "redirect:/shoppingproductmarks/" + encodeUrlPathSegment(shoppingProductMark.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ShoppingProductMarkController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ShoppingProductMark());
        return "shoppingproductmarks/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ShoppingProductMarkController.show(@PathVariable("id") Integer id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("shoppingproductmark", ShoppingProductMark.findShoppingProductMark(id));
        uiModel.addAttribute("itemId", id);
        return "shoppingproductmarks/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ShoppingProductMarkController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("shoppingproductmarks", ShoppingProductMark.findShoppingProductMarkEntries(firstResult, sizeNo));
            float nrOfPages = (float) ShoppingProductMark.countShoppingProductMarks() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("shoppingproductmarks", ShoppingProductMark.findAllShoppingProductMarks());
        }
        addDateTimeFormatPatterns(uiModel);
        return "shoppingproductmarks/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShoppingProductMarkController.update(@Valid ShoppingProductMark shoppingProductMark, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shoppingProductMark);
            return "shoppingproductmarks/update";
        }
        uiModel.asMap().clear();
        shoppingProductMark.merge();
        return "redirect:/shoppingproductmarks/" + encodeUrlPathSegment(shoppingProductMark.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShoppingProductMarkController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShoppingProductMark.findShoppingProductMark(id));
        return "shoppingproductmarks/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShoppingProductMarkController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShoppingProductMark shoppingProductMark = ShoppingProductMark.findShoppingProductMark(id);
        shoppingProductMark.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shoppingproductmarks";
    }
    
    void ShoppingProductMarkController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("shoppingProductMark_createdat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shoppingProductMark_updatedat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
    }
    
    void ShoppingProductMarkController.populateEditForm(Model uiModel, ShoppingProductMark shoppingProductMark) {
        uiModel.addAttribute("shoppingProductMark", shoppingProductMark);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("shoppingproductses", ShoppingProducts.findAllShoppingProductses());
    }
    
    String ShoppingProductMarkController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
