// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.domain.ShopOrderRetrun;
import com.huazhuo.shop.domain.ShopOrderReturnConsult;
import com.huazhuo.shop.domain.ShopOrderReturnImg;

privileged aspect ShopOrderReturnConsultController_Roo_Controller {
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ShopOrderReturnConsultController.show(@PathVariable("id") Integer id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("shoporderreturnconsult", ShopOrderReturnConsult.findShopOrderReturnConsult(id));
        uiModel.addAttribute("itemId", id);
        return "shoporderreturnconsults/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ShopOrderReturnConsultController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("shoporderreturnconsults", ShopOrderReturnConsult.findShopOrderReturnConsultEntries(firstResult, sizeNo));
            float nrOfPages = (float) ShopOrderReturnConsult.countShopOrderReturnConsults() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("shoporderreturnconsults", ShopOrderReturnConsult.findAllShopOrderReturnConsults());
        }
        addDateTimeFormatPatterns(uiModel);
        return "shoporderreturnconsults/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShopOrderReturnConsultController.update(@Valid ShopOrderReturnConsult shopOrderReturnConsult, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderReturnConsult);
            return "shoporderreturnconsults/update";
        }
        uiModel.asMap().clear();
        shopOrderReturnConsult.merge();
        return "redirect:/shoporderreturnconsults/" + encodeUrlPathSegment(shopOrderReturnConsult.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShopOrderReturnConsultController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShopOrderReturnConsult.findShopOrderReturnConsult(id));
        return "shoporderreturnconsults/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShopOrderReturnConsultController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShopOrderReturnConsult shopOrderReturnConsult = ShopOrderReturnConsult.findShopOrderReturnConsult(id);
        shopOrderReturnConsult.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shoporderreturnconsults";
    }
    
    void ShopOrderReturnConsultController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("shopOrderReturnConsult_createdat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrderReturnConsult_updatedat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
    }
    
    void ShopOrderReturnConsultController.populateEditForm(Model uiModel, ShopOrderReturnConsult shopOrderReturnConsult) {
        uiModel.addAttribute("shopOrderReturnConsult", shopOrderReturnConsult);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("shoporderretruns", ShopOrderRetrun.findAllShopOrderRetruns());
        uiModel.addAttribute("shoporderreturnimgs", ShopOrderReturnImg.findAllShopOrderReturnImgs());
    }
    
    String ShopOrderReturnConsultController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
