// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.domain.ShopOrderRetrun;
import com.huazhuo.shop.domain.ShopOrderReturnConsult;
import com.huazhuo.shop.domain.ShopOrders;
import com.huazhuo.shop.enumtype.ShopOrderRetrunType;

privileged aspect ShopOrderRetrunController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ShopOrderRetrunController.create(@Valid ShopOrderRetrun shopOrderRetrun, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderRetrun);
            return "shoporderretruns/create";
        }
        uiModel.asMap().clear();
        shopOrderRetrun.persist();
        return "redirect:/shoporderretruns/" + encodeUrlPathSegment(shopOrderRetrun.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ShopOrderRetrunController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ShopOrderRetrun());
        return "shoporderretruns/create";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShopOrderRetrunController.update(@Valid ShopOrderRetrun shopOrderRetrun, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderRetrun);
            return "shoporderretruns/update";
        }
        uiModel.asMap().clear();
        shopOrderRetrun.merge();
        return "redirect:/shoporderretruns/" + encodeUrlPathSegment(shopOrderRetrun.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShopOrderRetrunController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShopOrderRetrun.findShopOrderRetrun(id));
        return "shoporderretruns/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShopOrderRetrunController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShopOrderRetrun shopOrderRetrun = ShopOrderRetrun.findShopOrderRetrun(id);
        shopOrderRetrun.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shoporderretruns";
    }
    
    void ShopOrderRetrunController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("shopOrderRetrun_returntime_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrderRetrun_createdat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrderRetrun_updatedat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrderRetrun_shopagreetime_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
    }
    
    void ShopOrderRetrunController.populateEditForm(Model uiModel, ShopOrderRetrun shopOrderRetrun) {
        uiModel.addAttribute("shopOrderRetrun", shopOrderRetrun);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("shoporderreturnconsults", ShopOrderReturnConsult.findAllShopOrderReturnConsults());
        uiModel.addAttribute("shoporderses", ShopOrders.findAllShopOrderses());
        uiModel.addAttribute("shoporderretruntypes", ShopOrderRetrunType.findAllShopOrderRetrunTypes());
    }
    
    String ShopOrderRetrunController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
