// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.domain.MobileUsers;
import com.huazhuo.shop.domain.ShopFastMail;
import com.huazhuo.shop.domain.ShopOrderList;
import com.huazhuo.shop.domain.ShopOrders;
import com.huazhuo.shop.enumtype.LogisticsCompany;
import com.huazhuo.shop.enumtype.ShopOrderType;

privileged aspect ShopOrdersController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ShopOrdersController.create(@Valid ShopOrders shopOrders, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrders);
            return "shoporderses/create";
        }
        uiModel.asMap().clear();
        shopOrders.persist();
        return "redirect:/shoporderses/" + encodeUrlPathSegment(shopOrders.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ShopOrdersController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ShopOrders());
        return "shoporderses/create";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShopOrdersController.update(@Valid ShopOrders shopOrders, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrders);
            return "shoporderses/update";
        }
        uiModel.asMap().clear();
        shopOrders.merge();
        return "redirect:/shoporderses/" + encodeUrlPathSegment(shopOrders.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShopOrdersController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShopOrders.findShopOrders(id));
        return "shoporderses/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShopOrdersController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShopOrders shopOrders = ShopOrders.findShopOrders(id);
        shopOrders.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shoporderses";
    }
    
    void ShopOrdersController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("shopOrders_ordertime_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrders_payedat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrders_sendtime_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrders_endtime_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrders_createdat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("shopOrders_updatedat_date_format", DateTimeFormat.patternForStyle("MM", LocaleContextHolder.getLocale()));
    }
    
    void ShopOrdersController.populateEditForm(Model uiModel, ShopOrders shopOrders) {
        uiModel.addAttribute("shopOrders", shopOrders);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("mobileuserses", MobileUsers.findAllMobileUserses());
        uiModel.addAttribute("shopfastmails", ShopFastMail.findAllShopFastMails());
        uiModel.addAttribute("shoporderlists", ShopOrderList.findAllShopOrderLists());
        uiModel.addAttribute("logisticscompanys", LogisticsCompany.findAllLogisticsCompanys());
        uiModel.addAttribute("shopordertypes", ShopOrderType.findAllShopOrderTypes());
    }
    
    String ShopOrdersController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
