// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.domain.ShopOrderEvaluate;
import com.huazhuo.shop.domain.ShopOrderEvaluateImg;

privileged aspect ShopOrderEvaluateImgController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ShopOrderEvaluateImgController.create(@Valid ShopOrderEvaluateImg shopOrderEvaluateImg, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderEvaluateImg);
            return "shoporderevaluateimgs/create";
        }
        uiModel.asMap().clear();
        shopOrderEvaluateImg.persist();
        return "redirect:/shoporderevaluateimgs/" + encodeUrlPathSegment(shopOrderEvaluateImg.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ShopOrderEvaluateImgController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ShopOrderEvaluateImg());
        return "shoporderevaluateimgs/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ShopOrderEvaluateImgController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("shoporderevaluateimg", ShopOrderEvaluateImg.findShopOrderEvaluateImg(id));
        uiModel.addAttribute("itemId", id);
        return "shoporderevaluateimgs/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ShopOrderEvaluateImgController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("shoporderevaluateimgs", ShopOrderEvaluateImg.findShopOrderEvaluateImgEntries(firstResult, sizeNo));
            float nrOfPages = (float) ShopOrderEvaluateImg.countShopOrderEvaluateImgs() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("shoporderevaluateimgs", ShopOrderEvaluateImg.findAllShopOrderEvaluateImgs());
        }
        return "shoporderevaluateimgs/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ShopOrderEvaluateImgController.update(@Valid ShopOrderEvaluateImg shopOrderEvaluateImg, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, shopOrderEvaluateImg);
            return "shoporderevaluateimgs/update";
        }
        uiModel.asMap().clear();
        shopOrderEvaluateImg.merge();
        return "redirect:/shoporderevaluateimgs/" + encodeUrlPathSegment(shopOrderEvaluateImg.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ShopOrderEvaluateImgController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ShopOrderEvaluateImg.findShopOrderEvaluateImg(id));
        return "shoporderevaluateimgs/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ShopOrderEvaluateImgController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ShopOrderEvaluateImg shopOrderEvaluateImg = ShopOrderEvaluateImg.findShopOrderEvaluateImg(id);
        shopOrderEvaluateImg.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/shoporderevaluateimgs";
    }
    
    void ShopOrderEvaluateImgController.populateEditForm(Model uiModel, ShopOrderEvaluateImg shopOrderEvaluateImg) {
        uiModel.addAttribute("shopOrderEvaluateImg", shopOrderEvaluateImg);
        uiModel.addAttribute("shoporderevaluates", ShopOrderEvaluate.findAllShopOrderEvaluates());
    }
    
    String ShopOrderEvaluateImgController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
