// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.web.security;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import com.huazhuo.shop.security.BackGroups;

privileged aspect BackGroupsController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String BackGroupsController.create(@Valid BackGroups backGroups, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, backGroups);
            return "backgroupses/create";
        }
        uiModel.asMap().clear();
        backGroups.persist();
        return "redirect:/backgroupses/" + encodeUrlPathSegment(backGroups.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String BackGroupsController.createForm(Model uiModel) {
        populateEditForm(uiModel, new BackGroups());
        return "backgroupses/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String BackGroupsController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("backgroups", BackGroups.findBackGroups(id));
        uiModel.addAttribute("itemId", id);
        return "backgroupses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String BackGroupsController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("backgroupses", BackGroups.findBackGroupsEntries(firstResult, sizeNo));
            float nrOfPages = (float) BackGroups.countBackGroupses() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("backgroupses", BackGroups.findAllBackGroupses());
        }
        return "backgroupses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String BackGroupsController.update(@Valid BackGroups backGroups, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, backGroups);
            return "backgroupses/update";
        }
        uiModel.asMap().clear();
        backGroups.merge();
        return "redirect:/backgroupses/" + encodeUrlPathSegment(backGroups.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String BackGroupsController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, BackGroups.findBackGroups(id));
        return "backgroupses/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String BackGroupsController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        BackGroups backGroups = BackGroups.findBackGroups(id);
        backGroups.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/backgroupses";
    }
    
    void BackGroupsController.populateEditForm(Model uiModel, BackGroups backGroups) {
        uiModel.addAttribute("backGroups", backGroups);
    }
    
    String BackGroupsController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
