// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.city;


privileged aspect Areas_Roo_JavaBean {
    
    public String Areas.getCityId() {
        return this.cityId;
    }
    
    public void Areas.setCityId(String cityId) {
        this.cityId = cityId;
    }
    
    public String Areas.getCityName() {
        return this.cityName;
    }
    
    public void Areas.setCityName(String cityName) {
        this.cityName = cityName;
    }
    
    public String Areas.getAreaName() {
        return this.areaName;
    }
    
    public void Areas.setAreaName(String areaName) {
        this.areaName = areaName;
    }
    
    public String Areas.getProvinceId() {
        return this.provinceId;
    }
    
    public void Areas.setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }
    
    public String Areas.getSpell() {
        return this.spell;
    }
    
    public void Areas.setSpell(String spell) {
        this.spell = spell;
    }
    
}
