// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.city;

import java.util.Date;

privileged aspect Cities_Roo_JavaBean {
    
    public String Cities.getName() {
        return this.name;
    }
    
    public void Cities.setName(String name) {
        this.name = name;
    }
    
    public String Cities.getPinyin() {
        return this.pinyin;
    }
    
    public void Cities.setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }
    
    public String Cities.getPinyinAbridge() {
        return this.pinyinAbridge;
    }
    
    public void Cities.setPinyinAbridge(String pinyinAbridge) {
        this.pinyinAbridge = pinyinAbridge;
    }
    
    public String Cities.getInitial() {
        return this.initial;
    }
    
    public void Cities.setInitial(String initial) {
        this.initial = initial;
    }
    
    public String Cities.getZipcode() {
        return this.zipcode;
    }
    
    public void Cities.setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    
    public Integer Cities.getStatus() {
        return this.status;
    }
    
    public void Cities.setStatus(Integer status) {
        this.status = status;
    }
    
    public Date Cities.getCreatedAt() {
        return this.createdAt;
    }
    
    public void Cities.setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    
    public Date Cities.getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void Cities.setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public Integer Cities.getCount() {
        return this.count;
    }
    
    public void Cities.setCount(Integer count) {
        this.count = count;
    }
    
    public String Cities.getCityCode() {
        return this.cityCode;
    }
    
    public void Cities.setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }
    
    public String Cities.getWeather() {
        return this.weather;
    }
    
    public void Cities.setWeather(String weather) {
        this.weather = weather;
    }
    
    public String Cities.getTemperature() {
        return this.temperature;
    }
    
    public void Cities.setTemperature(String temperature) {
        this.temperature = temperature;
    }
    
    public String Cities.getPmTwoPointFive() {
        return this.pmTwoPointFive;
    }
    
    public void Cities.setPmTwoPointFive(String pmTwoPointFive) {
        this.pmTwoPointFive = pmTwoPointFive;
    }
    
    public String Cities.getCurrentTemperature() {
        return this.currentTemperature;
    }
    
    public void Cities.setCurrentTemperature(String currentTemperature) {
        this.currentTemperature = currentTemperature;
    }
    
    public String Cities.getHint() {
        return this.hint;
    }
    
    public void Cities.setHint(String hint) {
        this.hint = hint;
    }
    
    public Provinces Cities.getProvinces() {
        return this.provinces;
    }
    
    public void Cities.setProvinces(Provinces provinces) {
        this.provinces = provinces;
    }
    
}
