// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.city;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect Provinces_Roo_Jpa_Entity {
    
    declare @type: Provinces: @Entity;
    
    declare @type: Provinces: @Table(name = "provinces");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer Provinces.id;
    
    @Version
    @Column(name = "version")
    private Integer Provinces.version;
    
    public Integer Provinces.getId() {
        return this.id;
    }
    
    public void Provinces.setId(Integer id) {
        this.id = id;
    }
    
    public Integer Provinces.getVersion() {
        return this.version;
    }
    
    public void Provinces.setVersion(Integer version) {
        this.version = version;
    }
    
}
