// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.city;


privileged aspect Provinces_Roo_JavaBean {
    
    public String Provinces.getProvinceName() {
        return this.provinceName;
    }
    
    public void Provinces.setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }
    
    public String Provinces.getIndexId() {
        return this.indexId;
    }
    
    public void Provinces.setIndexId(String indexId) {
        this.indexId = indexId;
    }
    
    public String Provinces.getSpell() {
        return this.spell;
    }
    
    public void Provinces.setSpell(String spell) {
        this.spell = spell;
    }
    
    public Locality Provinces.getLocality() {
        return this.locality;
    }
    
    public void Provinces.setLocality(Locality locality) {
        this.locality = locality;
    }
    
}
