// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.enumtype;


privileged aspect ShopOrderRetrunType_Roo_JavaBean {
    
    public String ShopOrderRetrunType.getName() {
        return this.name;
    }
    
    public void ShopOrderRetrunType.setName(String name) {
        this.name = name;
    }
    
}
