// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.GsBigcategoryGoodscategoryRela;
import java.util.Date;

privileged aspect GsBigcategoryGoodscategoryRela_Roo_JavaBean {
    
    public Integer GsBigcategoryGoodscategoryRela.getGsBigcategoryId() {
        return this.gsBigcategoryId;
    }
    
    public void GsBigcategoryGoodscategoryRela.setGsBigcategoryId(Integer gsBigcategoryId) {
        this.gsBigcategoryId = gsBigcategoryId;
    }
    
    public Integer GsBigcategoryGoodscategoryRela.getShoppingCategoriesId() {
        return this.shoppingCategoriesId;
    }
    
    public void GsBigcategoryGoodscategoryRela.setShoppingCategoriesId(Integer shoppingCategoriesId) {
        this.shoppingCategoriesId = shoppingCategoriesId;
    }
    
    public Date GsBigcategoryGoodscategoryRela.getCreateTime() {
        return this.createTime;
    }
    
    public void GsBigcategoryGoodscategoryRela.setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
}
