// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.GsBigcategory;
import java.util.Date;

privileged aspect GsBigcategory_Roo_JavaBean {
    
    public Integer GsBigcategory.getParentId() {
        return this.parentId;
    }
    
    public void GsBigcategory.setParentId(Integer parentId) {
        this.parentId = parentId;
    }
    
    public String GsBigcategory.getParentName() {
        return this.parentName;
    }
    
    public void GsBigcategory.setParentName(String parentName) {
        this.parentName = parentName;
    }
    
    public String GsBigcategory.getName() {
        return this.name;
    }
    
    public void GsBigcategory.setName(String name) {
        this.name = name;
    }
    
    public String GsBigcategory.getTempPic() {
        return this.tempPic;
    }
    
    public void GsBigcategory.setTempPic(String tempPic) {
        this.tempPic = tempPic;
    }
    
    public String GsBigcategory.getTempPicDesc() {
        return this.tempPicDesc;
    }
    
    public void GsBigcategory.setTempPicDesc(String tempPicDesc) {
        this.tempPicDesc = tempPicDesc;
    }
    
    public Date GsBigcategory.getCreateTime() {
        return this.createTime;
    }
    
    public void GsBigcategory.setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public Date GsBigcategory.getUpdateTime() {
        return this.updateTime;
    }
    
    public void GsBigcategory.setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    public String GsBigcategory.getEnabled() {
        return this.enabled;
    }
    
    public void GsBigcategory.setEnabled(String enabled) {
        this.enabled = enabled;
    }
    
    public Integer GsBigcategory.getSort() {
        return this.sort;
    }
    
    public void GsBigcategory.setSort(Integer sort) {
        this.sort = sort;
    }
    
    public Integer GsBigcategory.getIsRequired() {
        return this.isRequired;
    }
    
    public void GsBigcategory.setIsRequired(Integer isRequired) {
        this.isRequired = isRequired;
    }
    
}
