// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.GsBigcategory;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect GsBigcategory_Roo_Jpa_Entity {
    
    declare @type: GsBigcategory: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer GsBigcategory.id;
    
    @Version
    @Column(name = "version")
    private Integer GsBigcategory.version;
    
    public Integer GsBigcategory.getId() {
        return this.id;
    }
    
    public void GsBigcategory.setId(Integer id) {
        this.id = id;
    }
    
    public Integer GsBigcategory.getVersion() {
        return this.version;
    }
    
    public void GsBigcategory.setVersion(Integer version) {
        this.version = version;
    }
    
}
