// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.MobileUsersAuthLicePic;
import java.util.Date;

privileged aspect MobileUsersAuthLicePic_Roo_JavaBean {
    
    public Integer MobileUsersAuthLicePic.getMobileUsersAuthId() {
        return this.mobileUsersAuthId;
    }
    
    public void MobileUsersAuthLicePic.setMobileUsersAuthId(Integer mobileUsersAuthId) {
        this.mobileUsersAuthId = mobileUsersAuthId;
    }
    
    public String MobileUsersAuthLicePic.getLicePic() {
        return this.licePic;
    }
    
    public void MobileUsersAuthLicePic.setLicePic(String licePic) {
        this.licePic = licePic;
    }
    
    public Date MobileUsersAuthLicePic.getCreatetime() {
        return this.createtime;
    }
    
    public void MobileUsersAuthLicePic.setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    public Date MobileUsersAuthLicePic.getUpdatetime() {
        return this.updatetime;
    }
    
    public void MobileUsersAuthLicePic.setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    
}
