// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.util.Date;

import com.huazhuo.shop.domain.MobileUsersAuth;

privileged aspect MobileUsersAuth_Roo_JavaBean {
	 public Integer MobileUsersAuth.getBSignatureNot() {
	        return this.bSignatureNot;
	    }
	    
	    public void MobileUsersAuth.setBSignatureNot(Integer bSignatureNot) {
	        this.bSignatureNot = bSignatureNot;
	    }
    public Integer MobileUsersAuth.getUserId() {
        return this.userId;
    }
    
    public void MobileUsersAuth.setUserId(Integer userId) {
        this.userId = userId;
    }
    
    public String MobileUsersAuth.getAuthStatus() {
        return this.authStatus;
    }
    
    public void MobileUsersAuth.setAuthStatus(String authStatus) {
        this.authStatus = authStatus;
    }
    
    public String MobileUsersAuth.getAuthRole() {
        return this.authRole;
    }
    
    public void MobileUsersAuth.setAuthRole(String authRole) {
        this.authRole = authRole;
    }
    
    public Integer MobileUsersAuth.getRelaOtherUserId() {
        return this.relaOtherUserId;
    }
    
    public void MobileUsersAuth.setRelaOtherUserId(Integer relaOtherUserId) {
        this.relaOtherUserId = relaOtherUserId;
    }
    
    public String MobileUsersAuth.getAuthName() {
        return this.authName;
    }
    
    public void MobileUsersAuth.setAuthName(String authName) {
        this.authName = authName;
    }
    
    public Integer MobileUsersAuth.getAuthProvince() {
        return this.authProvince;
    }
    
    public void MobileUsersAuth.setAuthProvince(Integer authProvince) {
        this.authProvince = authProvince;
    }
    
    public Integer MobileUsersAuth.getAuthCity() {
        return this.authCity;
    }
    
    public void MobileUsersAuth.setAuthCity(Integer authCity) {
        this.authCity = authCity;
    }
    
    public Integer MobileUsersAuth.getAuthCounty() {
        return this.authCounty;
    }
    
    public void MobileUsersAuth.setAuthCounty(Integer authCounty) {
        this.authCounty = authCounty;
    }
    
    public String MobileUsersAuth.getAuthorAddress() {
        return this.authorAddress;
    }
    
    public void MobileUsersAuth.setAuthorAddress(String authorAddress) {
        this.authorAddress = authorAddress;
    }
    
    public Date MobileUsersAuth.getCreateTime() {
        return this.createTime;
    }
    
    public void MobileUsersAuth.setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public String MobileUsersAuth.getAuthReasion() {
        return this.authReasion;
    }
    
    public void MobileUsersAuth.setAuthReasion(String authReasion) {
        this.authReasion = authReasion;
    }
    
    public Integer MobileUsersAuth.getSignatureStatus() {
        return this.signatureStatus;
    }
    
    public void MobileUsersAuth.setSignatureStatus(Integer signatureStatus) {
        this.signatureStatus = signatureStatus;
    }
    
    public Date MobileUsersAuth.getBSignatureTime() {
        return this.bSignatureTime;
    }
    
    public void MobileUsersAuth.setBSignatureTime(Date bSignatureTime) {
        this.bSignatureTime = bSignatureTime;
    }
    
    public String MobileUsersAuth.getSignatureRejectReason() {
        return this.signatureRejectReason;
    }
    
    public void MobileUsersAuth.setSignatureRejectReason(String signatureRejectReason) {
        this.signatureRejectReason = signatureRejectReason;
    }
    
    public Date MobileUsersAuth.getB_submitApplyTime() {
        return this.b_submitApplyTime;
    }
    
    public void MobileUsersAuth.setB_submitApplyTime(Date b_submitApplyTime) {
        this.b_submitApplyTime = b_submitApplyTime;
    }
    
    public String MobileUsersAuth.getRecommondPhone() {
        return this.recommondPhone;
    }
    
    public void MobileUsersAuth.setRecommondPhone(String recommondPhone) {
        this.recommondPhone = recommondPhone;
    }
    public Date MobileUsersAuth.getLastContractUpdateTime() {
        return this.lastContractUpdateTime;
    }
    
    public void MobileUsersAuth.setLastContractUpdateTime(Date lastContractUpdateTime) {
        this.lastContractUpdateTime = lastContractUpdateTime;
    }
    
}
