// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;


privileged aspect MobileUsers_Roo_JavaBean {
    
    public String MobileUsers.getUserName() {
        return this.userName;
    }
    
    public void MobileUsers.setUserName(String userName) {
        this.userName = userName;
    }
    
}
