// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.MobileUsersAuth;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect MobileUsersAuth_Roo_Jpa_Entity {
    
    declare @type: MobileUsersAuth: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer MobileUsersAuth.id;
    
    @Version
    @Column(name = "version")
    private Integer MobileUsersAuth.version;
    
    public Integer MobileUsersAuth.getId() {
        return this.id;
    }
    
    public void MobileUsersAuth.setId(Integer id) {
        this.id = id;
    }
    
    public Integer MobileUsersAuth.getVersion() {
        return this.version;
    }
    
    public void MobileUsersAuth.setVersion(Integer version) {
        this.version = version;
    }
    
}
