// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.ProductBrandShoppingCategoriesRela;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductBrandShoppingCategoriesRela_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ProductBrandShoppingCategoriesRela.entityManager;
    
    public static final EntityManager ProductBrandShoppingCategoriesRela.entityManager() {
        EntityManager em = new ProductBrandShoppingCategoriesRela().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ProductBrandShoppingCategoriesRela.countProductBrandShoppingCategoriesRelas() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ProductBrandShoppingCategoriesRela o", Long.class).getSingleResult();
    }
    
    public static List<ProductBrandShoppingCategoriesRela> ProductBrandShoppingCategoriesRela.findAllProductBrandShoppingCategoriesRelas() {
        return entityManager().createQuery("SELECT o FROM ProductBrandShoppingCategoriesRela o", ProductBrandShoppingCategoriesRela.class).getResultList();
    }
    
    public static ProductBrandShoppingCategoriesRela ProductBrandShoppingCategoriesRela.findProductBrandShoppingCategoriesRela(Integer id) {
        if (id == null) return null;
        return entityManager().find(ProductBrandShoppingCategoriesRela.class, id);
    }
    
    public static List<ProductBrandShoppingCategoriesRela> ProductBrandShoppingCategoriesRela.findProductBrandShoppingCategoriesRelaEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ProductBrandShoppingCategoriesRela o", ProductBrandShoppingCategoriesRela.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ProductBrandShoppingCategoriesRela.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ProductBrandShoppingCategoriesRela.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ProductBrandShoppingCategoriesRela attached = ProductBrandShoppingCategoriesRela.findProductBrandShoppingCategoriesRela(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ProductBrandShoppingCategoriesRela.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ProductBrandShoppingCategoriesRela.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ProductBrandShoppingCategoriesRela ProductBrandShoppingCategoriesRela.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ProductBrandShoppingCategoriesRela merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
