// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.ProductBrandShoppingCategoriesRela;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect ProductBrandShoppingCategoriesRela_Roo_Jpa_Entity {
    
    declare @type: ProductBrandShoppingCategoriesRela: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ProductBrandShoppingCategoriesRela.id;
    
    @Version
    @Column(name = "version")
    private Integer ProductBrandShoppingCategoriesRela.version;
    
    public Integer ProductBrandShoppingCategoriesRela.getId() {
        return this.id;
    }
    
    public void ProductBrandShoppingCategoriesRela.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ProductBrandShoppingCategoriesRela.getVersion() {
        return this.version;
    }
    
    public void ProductBrandShoppingCategoriesRela.setVersion(Integer version) {
        this.version = version;
    }
    
}
