// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.math.BigDecimal;
import java.util.List;

privileged aspect ShopFreightTemplateDetail_Roo_JavaBean {
    
    public Integer ShopFreightTemplateDetail.getCount() {
        return this.count;
    }
    
    public void ShopFreightTemplateDetail.setCount(Integer count) {
        this.count = count;
    }
    
    public BigDecimal ShopFreightTemplateDetail.getFreight() {
        return this.freight;
    }
    
    public void ShopFreightTemplateDetail.setFreight(BigDecimal freight) {
        this.freight = freight;
    }
    
    public Integer ShopFreightTemplateDetail.getAddCount() {
        return this.addCount;
    }
    
    public void ShopFreightTemplateDetail.setAddCount(Integer addCount) {
        this.addCount = addCount;
    }
    
    public BigDecimal ShopFreightTemplateDetail.getAddFreight() {
        return this.addFreight;
    }
    
    public void ShopFreightTemplateDetail.setAddFreight(BigDecimal addFreight) {
        this.addFreight = addFreight;
    }
    
    public ShopFreightTemplate ShopFreightTemplateDetail.getShopFreightTemplate() {
        return this.shopFreightTemplate;
    }
    
    public void ShopFreightTemplateDetail.setShopFreightTemplate(ShopFreightTemplate shopFreightTemplate) {
        this.shopFreightTemplate = shopFreightTemplate;
    }
    
    public List<ShopFreightTemplateDetailCity> ShopFreightTemplateDetail.getShopFreightTemplateDetailCities() {
        return this.shopFreightTemplateDetailCities;
    }
    
    public void ShopFreightTemplateDetail.setShopFreightTemplateDetailCities(List<ShopFreightTemplateDetailCity> shopFreightTemplateDetailCities) {
        this.shopFreightTemplateDetailCities = shopFreightTemplateDetailCities;
    }
    
}
