// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect ShopOrderReturnImg_Roo_Jpa_Entity {
    
    declare @type: ShopOrderReturnImg: @Entity;
    
    declare @type: ShopOrderReturnImg: @Table(name = "shop_order_retrun_img");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ShopOrderReturnImg.id;
    
    @Version
    @Column(name = "version")
    private Integer ShopOrderReturnImg.version;
    
    public Integer ShopOrderReturnImg.getId() {
        return this.id;
    }
    
    public void ShopOrderReturnImg.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ShopOrderReturnImg.getVersion() {
        return this.version;
    }
    
    public void ShopOrderReturnImg.setVersion(Integer version) {
        this.version = version;
    }
    
}
