// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.ShopCategoryCommissionRela;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ShopCategoryCommissionRela_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ShopCategoryCommissionRela.entityManager;
    
    public static final EntityManager ShopCategoryCommissionRela.entityManager() {
        EntityManager em = new ShopCategoryCommissionRela().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ShopCategoryCommissionRela.countShopCategoryCommissionRelas() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ShopCategoryCommissionRela o", Long.class).getSingleResult();
    }
    
    public static List<ShopCategoryCommissionRela> ShopCategoryCommissionRela.findAllShopCategoryCommissionRelas() {
        return entityManager().createQuery("SELECT o FROM ShopCategoryCommissionRela o", ShopCategoryCommissionRela.class).getResultList();
    }
    
    public static ShopCategoryCommissionRela ShopCategoryCommissionRela.findShopCategoryCommissionRela(Integer id) {
        if (id == null) return null;
        return entityManager().find(ShopCategoryCommissionRela.class, id);
    }
    
    public static List<ShopCategoryCommissionRela> ShopCategoryCommissionRela.findShopCategoryCommissionRelaEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ShopCategoryCommissionRela o", ShopCategoryCommissionRela.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ShopCategoryCommissionRela.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ShopCategoryCommissionRela.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ShopCategoryCommissionRela attached = ShopCategoryCommissionRela.findShopCategoryCommissionRela(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ShopCategoryCommissionRela.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ShopCategoryCommissionRela.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ShopCategoryCommissionRela ShopCategoryCommissionRela.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ShopCategoryCommissionRela merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
