// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect ShoppingProductsSpec_Roo_Jpa_Entity {
    
    declare @type: ShoppingProductsSpec: @Entity;
    
    declare @type: ShoppingProductsSpec: @Table(name = "shopping_products_spec");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ShoppingProductsSpec.id;
    
    @Version
    @Column(name = "version")
    private Integer ShoppingProductsSpec.version;
    
    public Integer ShoppingProductsSpec.getId() {
        return this.id;
    }
    
    public void ShoppingProductsSpec.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ShoppingProductsSpec.getVersion() {
        return this.version;
    }
    
    public void ShoppingProductsSpec.setVersion(Integer version) {
        this.version = version;
    }
    
}
