// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.ShopCategoryCommissionRela;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect ShopCategoryCommissionRela_Roo_JavaBean {
    
    public Integer ShopCategoryCommissionRela.getShopId() {
        return this.shopId;
    }
    
    public void ShopCategoryCommissionRela.setShopId(Integer shopId) {
        this.shopId = shopId;
    }
    
    public Integer ShopCategoryCommissionRela.getCategoryId() {
        return this.categoryId;
    }
    
    public void ShopCategoryCommissionRela.setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    
    public BigDecimal ShopCategoryCommissionRela.getCommissionRate() {
        return this.commissionRate;
    }
    
    public void ShopCategoryCommissionRela.setCommissionRate(BigDecimal commissionRate) {
        this.commissionRate = commissionRate;
    }
    
    public Date ShopCategoryCommissionRela.getCreateTime() {
        return this.createTime;
    }
    
    public void ShopCategoryCommissionRela.setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
}
