// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.util.Date;

privileged aspect ShopOrderReturnImg_Roo_JavaBean {
    
    public String ShopOrderReturnImg.getImgUrl() {
        return this.imgUrl;
    }
    
    public void ShopOrderReturnImg.setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    
    public Date ShopOrderReturnImg.getCreatedAt() {
        return this.createdAt;
    }
    
    public void ShopOrderReturnImg.setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    
    public Date ShopOrderReturnImg.getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void ShopOrderReturnImg.setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public ShopOrderReturnConsult ShopOrderReturnImg.getShopOrderReturnConsultId() {
        return this.shopOrderReturnConsultId;
    }
    
    public void ShopOrderReturnImg.setShopOrderReturnConsultId(ShopOrderReturnConsult shopOrderReturnConsultId) {
        this.shopOrderReturnConsultId = shopOrderReturnConsultId;
    }
    
}
