// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect ShopFreightTemplateDetail_Roo_Jpa_Entity {
    
    declare @type: ShopFreightTemplateDetail: @Entity;
    
    declare @type: ShopFreightTemplateDetail: @Table(name = "shop_freight_template_detail");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ShopFreightTemplateDetail.id;
    
    @Version
    @Column(name = "version")
    private Integer ShopFreightTemplateDetail.version;
    
    public Integer ShopFreightTemplateDetail.getId() {
        return this.id;
    }
    
    public void ShopFreightTemplateDetail.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ShopFreightTemplateDetail.getVersion() {
        return this.version;
    }
    
    public void ShopFreightTemplateDetail.setVersion(Integer version) {
        this.version = version;
    }
    
}
