// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.transaction.annotation.Transactional;

privileged aspect ShopOrderRetrun_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ShopOrderRetrun.entityManager;
    
    public static final EntityManager ShopOrderRetrun.entityManager() {
        EntityManager em = new ShopOrderRetrun().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ShopOrderRetrun.countShopOrderRetruns() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ShopOrderRetrun o", Long.class).getSingleResult();
    }
    
    public static List<ShopOrderRetrun> ShopOrderRetrun.findAllShopOrderRetruns() {
        return entityManager().createQuery("SELECT o FROM ShopOrderRetrun o", ShopOrderRetrun.class).getResultList();
    }
    
    public static ShopOrderRetrun ShopOrderRetrun.findShopOrderRetrun(Integer id) {
        if (id == null) return null;
        return entityManager().find(ShopOrderRetrun.class, id);
    }
    
    public static List<ShopOrderRetrun> ShopOrderRetrun.findShopOrderRetrunEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ShopOrderRetrun o", ShopOrderRetrun.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ShopOrderRetrun.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ShopOrderRetrun.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ShopOrderRetrun attached = ShopOrderRetrun.findShopOrderRetrun(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ShopOrderRetrun.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ShopOrderRetrun.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ShopOrderRetrun ShopOrderRetrun.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ShopOrderRetrun merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
