// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect ShopAddress_Roo_Jpa_Entity {
    
    declare @type: ShopAddress: @Entity;
    
    declare @type: ShopAddress: @Table(name = "shop_address");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ShopAddress.id;
    
    @Version
    @Column(name = "version")
    private Integer ShopAddress.version;
    
    public Integer ShopAddress.getId() {
        return this.id;
    }
    
    public void ShopAddress.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ShopAddress.getVersion() {
        return this.version;
    }
    
    public void ShopAddress.setVersion(Integer version) {
        this.version = version;
    }
    
}
