// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.util.Date;

privileged aspect ShopFastMail_Roo_JavaBean {
    
    public Integer ShopFastMail.getShopId() {
        return this.shopId;
    }
    
    public void ShopFastMail.setShopId(Integer shopId) {
        this.shopId = shopId;
    }
    
    public String ShopFastMail.getMailName() {
        return this.mailName;
    }
    
    public void ShopFastMail.setMailName(String mailName) {
        this.mailName = mailName;
    }
    
    public String ShopFastMail.getCost() {
        return this.cost;
    }
    
    public void ShopFastMail.setCost(String cost) {
        this.cost = cost;
    }
    
    public Integer ShopFastMail.getDefCheck() {
        return this.defCheck;
    }
    
    public void ShopFastMail.setDefCheck(Integer defCheck) {
        this.defCheck = defCheck;
    }
    
    public Date ShopFastMail.getCreatedAt() {
        return this.createdAt;
    }
    
    public void ShopFastMail.setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    
    public Date ShopFastMail.getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void ShopFastMail.setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public String ShopFastMail.getAtt1() {
        return this.att1;
    }
    
    public void ShopFastMail.setAtt1(String att1) {
        this.att1 = att1;
    }
    
    public String ShopFastMail.getAtt2() {
        return this.att2;
    }
    
    public void ShopFastMail.setAtt2(String att2) {
        this.att2 = att2;
    }
    
    public String ShopFastMail.getAtt3() {
        return this.att3;
    }
    
    public void ShopFastMail.setAtt3(String att3) {
        this.att3 = att3;
    }
    
    public String ShopFastMail.getAtt4() {
        return this.att4;
    }
    
    public void ShopFastMail.setAtt4(String att4) {
        this.att4 = att4;
    }
    
    public String ShopFastMail.getAtt5() {
        return this.att5;
    }
    
    public void ShopFastMail.setAtt5(String att5) {
        this.att5 = att5;
    }
    
}
