// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect ShoppingCategories_Roo_Jpa_Entity {
    
    declare @type: ShoppingCategories: @Entity;
    
    declare @type: ShoppingCategories: @Table(name = "shopping_categories");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ShoppingCategories.id;
    
    @Version
    @Column(name = "version")
    private Integer ShoppingCategories.version;
    
    public Integer ShoppingCategories.getId() {
        return this.id;
    }
    
    public void ShoppingCategories.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ShoppingCategories.getVersion() {
        return this.version;
    }
    
    public void ShoppingCategories.setVersion(Integer version) {
        this.version = version;
    }
    
}
