// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.math.BigDecimal;

privileged aspect ShoppingProductsSpec_Roo_JavaBean {

	    public Integer ShoppingProductsSpec.getWarningNum() {
	        return this.warningNum;
	    }
	    
	    public void ShoppingProductsSpec.setWarningNum(Integer warningNum) {
	        this.warningNum = warningNum;
	    }
    public Integer ShoppingProductsSpec.getProductsNum() {
        return this.productsNum;
    }
    
    public void ShoppingProductsSpec.setProductsNum(Integer productsNum) {
        this.productsNum = productsNum;
    }
    public String ShoppingProductsSpec.getSpecName() {
        return this.specName;
    }
    
    public void ShoppingProductsSpec.setSpecName(String specName) {
        this.specName = specName;
    }
    
    
    public BigDecimal ShoppingProductsSpec.getOrgPrice() {
        return this.orgPrice;
    }
    
    public void ShoppingProductsSpec.setOrgPrice(BigDecimal orgPrice) {
        this.orgPrice = orgPrice;
    }
    
    public BigDecimal ShoppingProductsSpec.getWeight() {
        return this.weight;
    }
    
    public void ShoppingProductsSpec.setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    
    public BigDecimal ShoppingProductsSpec.getPrice() {
        return this.price;
    }
    
    public void ShoppingProductsSpec.setPrice(BigDecimal price) {
        this.price = price;
    }
    
    public ShoppingProducts ShoppingProductsSpec.getShoppingProducts() {
        return this.shoppingProducts;
    }
    
    public void ShoppingProductsSpec.setShoppingProducts(ShoppingProducts shoppingProducts) {
        this.shoppingProducts = shoppingProducts;
    }
    
}
