// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;


privileged aspect ShoppingProductType_Roo_JavaBean {
    
    public ShoppingProducts ShoppingProductType.getShoppingProductsId() {
        return this.shoppingProductsId;
    }
    
    public void ShoppingProductType.setShoppingProductsId(ShoppingProducts shoppingProductsId) {
        this.shoppingProductsId = shoppingProductsId;
    }
    
    public String ShoppingProductType.getTypeName() {
        return this.typeName;
    }
    
    public void ShoppingProductType.setTypeName(String typeName) {
        this.typeName = typeName;
    }
    
    public String ShoppingProductType.getTypeValue() {
        return this.typeValue;
    }
    
    public void ShoppingProductType.setTypeValue(String typeValue) {
        this.typeValue = typeValue;
    }
    
}
