// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect ShoppingProducts_Roo_Jpa_Entity {
    
    declare @type: ShoppingProducts: @Entity;
    
    declare @type: ShoppingProducts: @Table(name = "shopping_products");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ShoppingProducts.id;
    
    @Version
    @Column(name = "version")
    private Integer ShoppingProducts.version;
    
    public Integer ShoppingProducts.getId() {
        return this.id;
    }
    
    public void ShoppingProducts.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ShoppingProducts.getVersion() {
        return this.version;
    }
    
    public void ShoppingProducts.setVersion(Integer version) {
        this.version = version;
    }
    
}
