// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.util.Date;

privileged aspect ShopOrderList_Roo_JavaBean {
    
    public ShopOrders ShopOrderList.getShopOrderId() {
        return this.shopOrderId;
    }
    
    public void ShopOrderList.setShopOrderId(ShopOrders shopOrderId) {
        this.shopOrderId = shopOrderId;
    }
    
    public Integer ShopOrderList.getBuyCouts() {
        return this.buyCouts;
    }
    
    public void ShopOrderList.setBuyCouts(Integer buyCouts) {
        this.buyCouts = buyCouts;
    }
    
    public ShoppingProducts ShopOrderList.getProductId() {
        return this.productId;
    }
    
    public void ShopOrderList.setProductId(ShoppingProducts productId) {
        this.productId = productId;
    }
    
    public String ShopOrderList.getProductName() {
        return this.productName;
    }
    
    public void ShopOrderList.setProductName(String productName) {
        this.productName = productName;
    }
    
    public String ShopOrderList.getProductProperty() {
        return this.productProperty;
    }
    
    public void ShopOrderList.setProductProperty(String productProperty) {
        this.productProperty = productProperty;
    }
    
    public String ShopOrderList.getPrice() {
        return this.price;
    }
    
    public void ShopOrderList.setPrice(String price) {
        this.price = price;
    }
    
    public Date ShopOrderList.getCreatedAt() {
        return this.createdAt;
    }
    
    public void ShopOrderList.setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    
    public Date ShopOrderList.getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void ShopOrderList.setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public String ShopOrderList.getAtt1() {
        return this.att1;
    }
    
    public void ShopOrderList.setAtt1(String att1) {
        this.att1 = att1;
    }
    
    public String ShopOrderList.getAtt2() {
        return this.att2;
    }
    
    public void ShopOrderList.setAtt2(String att2) {
        this.att2 = att2;
    }
    
    public String ShopOrderList.getAtt3() {
        return this.att3;
    }
    
    public void ShopOrderList.setAtt3(String att3) {
        this.att3 = att3;
    }
    
    public String ShopOrderList.getAtt4() {
        return this.att4;
    }
    
    public void ShopOrderList.setAtt4(String att4) {
        this.att4 = att4;
    }
    
    public String ShopOrderList.getAtt5() {
        return this.att5;
    }
    
    public void ShopOrderList.setAtt5(String att5) {
        this.att5 = att5;
    }
    
}
