// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import com.huazhuo.shop.domain.ShoppingProductsDetail;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect ShoppingProductsDetail_Roo_Jpa_Entity {
    
    declare @type: ShoppingProductsDetail: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ShoppingProductsDetail.id;
    
    @Version
    @Column(name = "version_")
    private Integer ShoppingProductsDetail.version_;
    
    public Integer ShoppingProductsDetail.getId() {
        return this.id;
    }
    
    public void ShoppingProductsDetail.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ShoppingProductsDetail.getVersion_() {
        return this.version_;
    }
    
    public void ShoppingProductsDetail.setVersion_(Integer version) {
        this.version_ = version;
    }
    
}
