// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.transaction.annotation.Transactional;

privileged aspect ShopOrderReturnConsult_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ShopOrderReturnConsult.entityManager;
    
    public static final EntityManager ShopOrderReturnConsult.entityManager() {
        EntityManager em = new ShopOrderReturnConsult().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ShopOrderReturnConsult.countShopOrderReturnConsults() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ShopOrderReturnConsult o", Long.class).getSingleResult();
    }
    
    public static List<ShopOrderReturnConsult> ShopOrderReturnConsult.findAllShopOrderReturnConsults() {
        return entityManager().createQuery("SELECT o FROM ShopOrderReturnConsult o", ShopOrderReturnConsult.class).getResultList();
    }
    
    public static ShopOrderReturnConsult ShopOrderReturnConsult.findShopOrderReturnConsult(Integer id) {
        if (id == null) return null;
        return entityManager().find(ShopOrderReturnConsult.class, id);
    }
    
    public static List<ShopOrderReturnConsult> ShopOrderReturnConsult.findShopOrderReturnConsultEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ShopOrderReturnConsult o", ShopOrderReturnConsult.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ShopOrderReturnConsult.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ShopOrderReturnConsult.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ShopOrderReturnConsult attached = ShopOrderReturnConsult.findShopOrderReturnConsult(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ShopOrderReturnConsult.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ShopOrderReturnConsult.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ShopOrderReturnConsult ShopOrderReturnConsult.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ShopOrderReturnConsult merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
