// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.domain;

import java.util.Date;

privileged aspect SpecialMarks_Roo_JavaBean {
    
    public String SpecialMarks.getName() {
        return this.name;
    }
    
    public void SpecialMarks.setName(String name) {
        this.name = name;
    }
    
    public Integer SpecialMarks.getMarkCategoryCodeGoods() {
        return this.markCategoryCodeGoods;
    }
    
    public void SpecialMarks.setMarkCategoryCodeGoods(Integer markCategoryCodeGoods) {
        this.markCategoryCodeGoods = markCategoryCodeGoods;
    }
    
    public Integer SpecialMarks.getMarkRangeCodeGoods() {
        return this.markRangeCodeGoods;
    }
    
    public void SpecialMarks.setMarkRangeCodeGoods(Integer markRangeCodeGoods) {
        this.markRangeCodeGoods = markRangeCodeGoods;
    }
    
    
    public Integer SpecialMarks.getEnabled() {
        return this.enabled;
    }
    
    public void SpecialMarks.setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
    
    
    
    public Date SpecialMarks.getCreatedAt() {
        return this.createdAt;
    }
    
    public void SpecialMarks.setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    
    public Date SpecialMarks.getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void SpecialMarks.setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
}
