// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.enumtype;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.transaction.annotation.Transactional;

privileged aspect ShopFreightTemplateType_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ShopFreightTemplateType.entityManager;
    
    public static final EntityManager ShopFreightTemplateType.entityManager() {
        EntityManager em = new ShopFreightTemplateType().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ShopFreightTemplateType.countShopFreightTemplateTypes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ShopFreightTemplateType o", Long.class).getSingleResult();
    }
    
    public static List<ShopFreightTemplateType> ShopFreightTemplateType.findAllShopFreightTemplateTypes() {
        return entityManager().createQuery("SELECT o FROM ShopFreightTemplateType o", ShopFreightTemplateType.class).getResultList();
    }
    
    public static ShopFreightTemplateType ShopFreightTemplateType.findShopFreightTemplateType(Integer id) {
        if (id == null) return null;
        return entityManager().find(ShopFreightTemplateType.class, id);
    }
    
    public static List<ShopFreightTemplateType> ShopFreightTemplateType.findShopFreightTemplateTypeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ShopFreightTemplateType o", ShopFreightTemplateType.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ShopFreightTemplateType.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ShopFreightTemplateType.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ShopFreightTemplateType attached = ShopFreightTemplateType.findShopFreightTemplateType(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ShopFreightTemplateType.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ShopFreightTemplateType.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ShopFreightTemplateType ShopFreightTemplateType.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ShopFreightTemplateType merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
