// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.enumtype;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect ShopOrderRetrunType_Roo_Jpa_Entity {
    
    declare @type: ShopOrderRetrunType: @Entity;
    
    declare @type: ShopOrderRetrunType: @Table(name = "shop_order_return_type");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer ShopOrderRetrunType.id;
    
    @Version
    @Column(name = "version")
    private Integer ShopOrderRetrunType.version;
    
    public Integer ShopOrderRetrunType.getId() {
        return this.id;
    }
    
    public void ShopOrderRetrunType.setId(Integer id) {
        this.id = id;
    }
    
    public Integer ShopOrderRetrunType.getVersion() {
        return this.version;
    }
    
    public void ShopOrderRetrunType.setVersion(Integer version) {
        this.version = version;
    }
    
}
