// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.enumtype;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.transaction.annotation.Transactional;

privileged aspect ShopOrderRetrunType_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ShopOrderRetrunType.entityManager;
    
    public static final EntityManager ShopOrderRetrunType.entityManager() {
        EntityManager em = new ShopOrderRetrunType().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ShopOrderRetrunType.countShopOrderRetrunTypes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ShopOrderRetrunType o", Long.class).getSingleResult();
    }
    
    public static List<ShopOrderRetrunType> ShopOrderRetrunType.findAllShopOrderRetrunTypes() {
        return entityManager().createQuery("SELECT o FROM ShopOrderRetrunType o", ShopOrderRetrunType.class).getResultList();
    }
    
    public static ShopOrderRetrunType ShopOrderRetrunType.findShopOrderRetrunType(Integer id) {
        if (id == null) return null;
        return entityManager().find(ShopOrderRetrunType.class, id);
    }
    
    public static List<ShopOrderRetrunType> ShopOrderRetrunType.findShopOrderRetrunTypeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ShopOrderRetrunType o", ShopOrderRetrunType.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ShopOrderRetrunType.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ShopOrderRetrunType.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ShopOrderRetrunType attached = ShopOrderRetrunType.findShopOrderRetrunType(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ShopOrderRetrunType.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ShopOrderRetrunType.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ShopOrderRetrunType ShopOrderRetrunType.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ShopOrderRetrunType merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
