// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.enumtype;


privileged aspect SysLogType_Roo_JavaBean {
    
    public String SysLogType.getName() {
        return this.name;
    }
    
    public void SysLogType.setName(String name) {
        this.name = name;
    }
    
    public Integer SysLogType.getState() {
        return this.state;
    }
    
    public void SysLogType.setState(Integer state) {
        this.state = state;
    }
    
}
