// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.security;


privileged aspect BackAuthority_Roo_JavaBean {
    
    public String BackAuthority.getAuthorityName() {
        return this.authorityName;
    }
    
    public void BackAuthority.setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
    }
    
    public String BackAuthority.getName() {
        return this.name;
    }
    
    public void BackAuthority.setName(String name) {
        this.name = name;
    }
    
}
