// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.security;

import java.util.Date;

privileged aspect BackUser_Roo_JavaBean {
    
    public String BackUser.getUserName() {
        return this.userName;
    }
    
    public void BackUser.setUserName(String userName) {
        this.userName = userName;
    }
    
    public String BackUser.getPhone() {
        return this.phone;
    }
    
    public void BackUser.setPhone(String phone) {
        this.phone = phone;
    }
    
    public String BackUser.getSmsToken() {
        return this.smsToken;
    }
    
    public void BackUser.setSmsToken(String smsToken) {
        this.smsToken = smsToken;
    }
    
    public String BackUser.getFullName() {
        return this.fullName;
    }
    
    public void BackUser.setFullName(String fullName) {
        this.fullName = fullName;
    }
    
    public String BackUser.getPassword() {
        return this.password;
    }
    
    public void BackUser.setPassword(String password) {
        this.password = password;
    }
    
    public String BackUser.getCompanyName() {
        return this.companyName;
    }
    
    public void BackUser.setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    
    public Integer BackUser.getProvincesId() {
        return this.provincesId;
    }
    
    public void BackUser.setProvincesId(Integer provincesId) {
        this.provincesId = provincesId;
    }
    
    public Integer BackUser.getCitiesId() {
        return this.citiesId;
    }
    
    public void BackUser.setCitiesId(Integer citiesId) {
        this.citiesId = citiesId;
    }
    
    public String BackUser.getAddress() {
        return this.address;
    }
    
    public void BackUser.setAddress(String address) {
        this.address = address;
    }
    
    public String BackUser.getContact() {
        return this.contact;
    }
    
    public void BackUser.setContact(String contact) {
        this.contact = contact;
    }
    
    public String BackUser.getEmail() {
        return this.email;
    }
    
    public void BackUser.setEmail(String email) {
        this.email = email;
    }
    
    public Boolean BackUser.getEnabled() {
        return this.enabled;
    }
    
    public void BackUser.setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    
    public Date BackUser.getCreatedTime() {
        return this.createdTime;
    }
    
    public void BackUser.setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    
    public Date BackUser.getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void BackUser.setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
    
    public Date BackUser.getEnabledTime() {
        return this.enabledTime;
    }
    
    public void BackUser.setEnabledTime(Date enabledTime) {
        this.enabledTime = enabledTime;
    }
    
}
