// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.security;


privileged aspect BackGroups_Roo_JavaBean {
    
    public String BackGroups.getGroupName() {
        return this.groupName;
    }
    
    public void BackGroups.setGroupName(String groupName) {
        this.groupName = groupName;
    }
    
}
