// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.security;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.transaction.annotation.Transactional;

privileged aspect BackGroups_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager BackGroups.entityManager;
    
    public static final EntityManager BackGroups.entityManager() {
        EntityManager em = new BackGroups().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long BackGroups.countBackGroupses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM BackGroups o", Long.class).getSingleResult();
    }
    
    public static List<BackGroups> BackGroups.findAllBackGroupses() {
        return entityManager().createQuery("SELECT o FROM BackGroups o", BackGroups.class).getResultList();
    }
    
    public static BackGroups BackGroups.findBackGroups(Integer id) {
        if (id == null) return null;
        return entityManager().find(BackGroups.class, id);
    }
    
    public static List<BackGroups> BackGroups.findBackGroupsEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM BackGroups o", BackGroups.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void BackGroups.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void BackGroups.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            BackGroups attached = BackGroups.findBackGroups(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void BackGroups.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void BackGroups.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public BackGroups BackGroups.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        BackGroups merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
