// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.security;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect BackUser_Roo_Jpa_Entity {
    
    declare @type: BackUser: @Entity;
    
    declare @type: BackUser: @Table(name = "back_user");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer BackUser.id;
    
    @Version
    @Column(name = "version")
    private Integer BackUser.version;
    
    public Integer BackUser.getId() {
        return this.id;
    }
    
    public void BackUser.setId(Integer id) {
        this.id = id;
    }
    
    public Integer BackUser.getVersion() {
        return this.version;
    }
    
    public void BackUser.setVersion(Integer version) {
        this.version = version;
    }
    
}
