// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.security;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

privileged aspect BackGroupAuthority_Roo_Jpa_Entity {
    
    declare @type: BackGroupAuthority: @Entity;
    
    declare @type: BackGroupAuthority: @Table(name = "back_group_authorities");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer BackGroupAuthority.id;
    
    @Version
    @Column(name = "version")
    private Integer BackGroupAuthority.version;
    
    public Integer BackGroupAuthority.getId() {
        return this.id;
    }
    
    public void BackGroupAuthority.setId(Integer id) {
        this.id = id;
    }
    
    public Integer BackGroupAuthority.getVersion() {
        return this.version;
    }
    
    public void BackGroupAuthority.setVersion(Integer version) {
        this.version = version;
    }
    
}
