// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.security;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.transaction.annotation.Transactional;

privileged aspect BackGroupMembers_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager BackGroupMembers.entityManager;
    
    public static final EntityManager BackGroupMembers.entityManager() {
        EntityManager em = new BackGroupMembers().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long BackGroupMembers.countBackGroupMemberses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM BackGroupMembers o", Long.class).getSingleResult();
    }
    
    public static List<BackGroupMembers> BackGroupMembers.findAllBackGroupMemberses() {
        return entityManager().createQuery("SELECT o FROM BackGroupMembers o", BackGroupMembers.class).getResultList();
    }
    
    public static BackGroupMembers BackGroupMembers.findBackGroupMembers(Integer id) {
        if (id == null) return null;
        return entityManager().find(BackGroupMembers.class, id);
    }
    
    public static List<BackGroupMembers> BackGroupMembers.findBackGroupMembersEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM BackGroupMembers o", BackGroupMembers.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void BackGroupMembers.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void BackGroupMembers.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            BackGroupMembers attached = BackGroupMembers.findBackGroupMembers(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void BackGroupMembers.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void BackGroupMembers.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public BackGroupMembers BackGroupMembers.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        BackGroupMembers merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
