// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.bill;

import java.math.BigDecimal;

import com.huazhuo.shop.billenum.BillEnumDetail;
import com.huazhuo.shop.domain.ShopOrders;

privileged aspect ShopBillDetail_Roo_JavaBean {
    
    public ShopOrders ShopBillDetail.getShopOrders() {
        return this.shopOrders;
    }
    
    public void ShopBillDetail.setShopOrders(ShopOrders shopOrders) {
        this.shopOrders = shopOrders;
    }
    
    public ShopBill ShopBillDetail.getShopBill() {
        return this.shopBill;
    }
    
    public void ShopBillDetail.setShopBill(ShopBill shopBill) {
        this.shopBill = shopBill;
    }
    
    public BillEnumDetail ShopBillDetail.getBillEnumDetail() {
        return this.billEnumDetail;
    }
    
    public void ShopBillDetail.setBillEnumDetail(BillEnumDetail billEnumDetail) {
        this.billEnumDetail = billEnumDetail;
    }
    
    public BigDecimal ShopBillDetail.getOrderCost() {
        return this.orderCost;
    }
    
    public void ShopBillDetail.setOrderCost(BigDecimal orderCost) {
        this.orderCost = orderCost;
    }
    
    public BigDecimal ShopBillDetail.getOrderSettleCost() {
        return this.orderSettleCost;
    }
    
    public void ShopBillDetail.setOrderSettleCost(BigDecimal orderSettleCost) {
        this.orderSettleCost = orderSettleCost;
    }
    
    public Boolean ShopBillDetail.getIsAdjustBill() {
        return this.isAdjustBill;
    }
    
    public void ShopBillDetail.setIsAdjustBill(Boolean isAdjustBill) {
        this.isAdjustBill = isAdjustBill;
    }
    
}
