// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.bill;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.springframework.transaction.annotation.Transactional;

privileged aspect ShopBillDetail_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ShopBillDetail.entityManager;
    
    public static final EntityManager ShopBillDetail.entityManager() {
        EntityManager em = new ShopBillDetail().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ShopBillDetail.countShopBillDetails() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ShopBillDetail o", Long.class).getSingleResult();
    }
    
    public static List<ShopBillDetail> ShopBillDetail.findAllShopBillDetails() {
        return entityManager().createQuery("SELECT o FROM ShopBillDetail o", ShopBillDetail.class).getResultList();
    }
    
    public static ShopBillDetail ShopBillDetail.findShopBillDetail(Integer id) {
        if (id == null) return null;
        return entityManager().find(ShopBillDetail.class, id);
    }
    
    public static List<ShopBillDetail> ShopBillDetail.findShopBillDetailEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ShopBillDetail o", ShopBillDetail.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ShopBillDetail.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ShopBillDetail.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ShopBillDetail attached = ShopBillDetail.findShopBillDetail(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ShopBillDetail.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ShopBillDetail.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ShopBillDetail ShopBillDetail.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ShopBillDetail merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
