// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.huazhuo.shop.log;

import java.util.Date;

import com.huazhuo.shop.enumtype.SysLogType;

privileged aspect SysLog_Roo_JavaBean {
	  public Integer SysLog.getOperatorType() {
	        return this.operatorType;
	    }
	    
	    public void SysLog.setOperatorType(Integer operatorType) {
	        this.operatorType = operatorType;
	    }
    
    public String SysLog.getContent() {
        return this.content;
    }
    
    public void SysLog.setContent(String content) {
        this.content = content;
    }
    
    public String SysLog.getOperator() {
        return this.operator;
    }
    
    public void SysLog.setOperator(String operator) {
        this.operator = operator;
    }
    
    public Integer SysLog.getProcessId() {
        return this.processId;
    }
    
    public void SysLog.setProcessId(Integer processId) {
        this.processId = processId;
    }
    
    public String SysLog.getIp() {
        return this.ip;
    }
    
    public void SysLog.setIp(String ip) {
        this.ip = ip;
    }
    
    public SysLogType SysLog.getSysLogType() {
        return this.sysLogType;
    }
    
    public void SysLog.setSysLogType(SysLogType sysLogType) {
        this.sysLogType = sysLogType;
    }
    
    public Date SysLog.getCreatedAt() {
        return this.createdAt;
    }
    
    public void SysLog.setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    
    public Date SysLog.getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void SysLog.setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public Boolean SysLog.getState() {
        return this.state;
    }
    
    public void SysLog.setState(Boolean state) {
        this.state = state;
    }
    
}
